{
  "hash": "56f971d0826db561aed52c48a12ab973",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Problem Set 1\"\nauthor: \"Michael Fehl, Xènia Alemany\"\ndesc: \"Network Measures & Random Graph Models\"\nformat:\n  html:\n    embed-resources: true\n  pdf:\n    toc: true\nproblem-set: true\nimage: /images/network_citations.png\neditor: \n  markdown: \n    wrap: 72\nexecute:\n  cache: true\n---\n\n# Libraries\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(R.matlab)   # read .mat files\nlibrary(igraph)     # network/graph funcs\nlibrary(tidyverse)  # clean data management\nlibrary(tidygraph)  # tidy wrapper around igraph objects \nlibrary(ggraph)     # ggplot for igraph objects\nlibrary(patchwork)  # stitch tidyverse graphs tg\nlibrary(furrr)      # optimize data pipeline\nlibrary(glue)       # printf\n```\n:::\n\n\n# 1 Network Measures\n\nA common property of social networks is that they have very small diameters relative to their total size. This property is sometimes called the \"small-world phenomenon\" and is the origin of the popular phrase \"six degrees of separation\". In class, we saw that a way to formalize small worlds was that the diameter $D$ is $O(log(n))$. In general, we think the property holds when the diameter grows less than linearly with n. For the following exercises, use the facebook small dataset:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"data loading\"}\nrm(list=ls())\n# iterate thru files in facebook_small\nfolder_path <- file.path(\"C:/Users/T14/7Programming/R/class/networks/problem_sets/ps01/data/facebook_small\")\nfile_list <- list.files(path = folder_path, \n                        pattern = \"\\\\.mat$\", \n                        full.names = TRUE)\n\nfacebook_graphs <- list() #init empty matrix\n\nfor (file in file_list){\n  clean_name <- tools::file_path_sans_ext(basename(file)) # extract school name\n  raw_mat <- readMat(file)                                # load in sparse matrix object\n  adj_matrix <- raw_mat$A                                 # extract adj matrix stored as \"A\"\n  tbl_g <- graph_from_adjacency_matrix(                   # convert to igraph object\n    adj_matrix, \n    mode = \"undirected\",\n    diag = FALSE # remove self-loops\n  ) %>% \n    as_tbl_graph()                                        # store as a tidy graph object -- memory efficient\n  facebook_graphs[[clean_name]] <- tbl_g                  # object store in list, end of iteration\n}\n\nrm(raw_mat, adj_matrix, tbl_g)                            # rm temporary objects -- free up memory\ngc()\n```\n:::\n\n\n## (a) Compute Diameters & Distances\n\n(a) For each network, compute the diameter $\\ell_{max}$ of the largest component of the network and the mean geodesic distance ⟨$\\ell$⟩ between pairs of vertices in the largest component of the network.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"test on subset\"}\n# test on single matrix\ntest <- facebook_graphs$American75\ng <- largest_component(test) # extract largest component\ndia <- diameter(g, weights=NA) # diameter\ndist <- mean_distance(g, weights=NA) # mean geo distance\nschool_name = names(facebook_graphs)[1]\n\ndata.frame(School = school_name,\n           Diameter = dia,\n           Mean_Distance = dist)\n\n# test on subset\nfinal_table <- list()\nschool_names <- names(facebook_graphs)\nsubset <- school_names[1:3]\n\nplan(multisession, workers = parallel::detectCores() - 1)\n\ntime_taken <- system.time({\n  final_table <- future_map_dfr(subset, function(school) {\n    library(igraph)\n    library(tidygraph)\n    \n    g_large <- largest_component(facebook_graphs[[school]])\n    data.frame(\n      School = school,\n      N = vcount(g_large),\n      Diameter = diameter(g_large, directed = FALSE, weights = NA),\n      Mean_Distance = mean_distance(g_large, directed = FALSE, weights = NA)\n    )\n  }, \n  .options = furrr_options(\n    seed = TRUE,\n    globals = list(facebook_graphs = facebook_graphs)  # explicitly export the data\n  ))\n})\n\nplan(sequential)\nprint(time_taken)\nprint(final_table)\n```\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"code for calculating diameter, mean dist\"}\nplan(multisession, workers = parallel::detectCores() - 1)\n\ntime_taken <- system.time({\n  final_table <- future_map(file_list, function(file) {\n    school <- tools::file_path_sans_ext(basename(file))\n    \n    tryCatch({\n      raw_mat <- readMat(file)\n      g <- graph_from_adjacency_matrix(raw_mat$A, \n                                       mode = \"undirected\", \n                                       diag = FALSE)\n      g_large <- largest_component(g)\n      \n      data.frame(\n        School = school,\n        N_lg_component = vcount(g_large),\n        N_total = vcount(g),\n        Diameter = diameter(g_large, \n                            directed = FALSE,\n                            weights = NA),\n        Mean_Distance = mean_distance(g_large, \n                                      directed = FALSE, \n                                      weights = NA)\n      )\n    }, error = function(e) {\n      data.frame(\n        School = school,\n        N_lg_component = NA,\n        N_total = NA,\n        Diameter = NA,\n        Mean_Distance = NA\n      )\n    })\n  }, .options = furrr_options(seed = TRUE, packages = c(\"igraph\", \"R.matlab\", \"tools\"))) |>\n    list_rbind()\n})\n\nplan(sequential) \nwrite_csv(final_table, \"facebook_network_measures.csv\") \nprint(time_taken)\nprint(final_table)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load in data: school, diam, mean dist, network size, largest comp size\nrm(list=ls())\ndf <- read_csv(\"data/facebook_network_measures.csv\")\ndf %>% \n  select(School, Diameter, Mean_Distance) %>% \n  mutate(Mean_Distance = round(Mean_Distance, 2)) %>% \n  head(n=8)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 x 3\n  School     Diameter Mean_Distance\n  <chr>         <dbl>         <dbl>\n1 American75        9          2.77\n2 Amherst41         7          2.4 \n3 Baylor93          7          2.67\n4 BC17              9          2.79\n5 Bingham82         8          2.82\n6 Bowdoin47         6          2.43\n7 Brandeis99        7          2.49\n8 Brown11           9          2.7 \n```\n\n\n:::\n:::\n\n\n## (b) Plot\n\n(b) Make two figures, one showing $\\ell_{max}$ versus network size $n$\n    and one showing ⟨$\\ell$⟩ versus the size of the largest component\n    $n$.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"plotting code\"}\n# dia vs network size\nfig1<-ggplot(data=df) +\n  geom_point(aes(x=N_total, y=Diameter)) +\n  theme_minimal() +\n  labs(\n    title = \"Network Diameter\",\n    x = \"Total Network Size (n)\",\n    y = expression(\"Diameter \" (l[max]))\n  ) +\n  theme_bw()+\n  theme(\n    plot.title = element_text(hjust=0.5)\n  )\n\n\n\n# dist v size of lg component g\nfig2<-ggplot(data=df) +\n  geom_point(aes(x=N_lg_component, y=Mean_Distance)) +\n  theme_minimal() +\n  labs(\n    title = \"Network Distance\",\n    x = \"Size of Largest Component g(n)\",\n    y = expression(\"Mean Distance  <l>\")\n  ) +\n  theme_bw()+\n  theme(\n    plot.title = element_text(hjust=0.5)\n  )\n\nfig1 + fig2\n```\n\n::: {.cell-output-display}\n![](problem_set_files/figure-pdf/unnamed-chunk-3-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n## (c) Six-Degrees\n\n(c) Comment on the degree to which these figures support the six-degrees of separation idea.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# update to add log(n) line to graphs\nfig1 +\n  geom_line(aes(x=N_total, y=log(N_total)), \n            color=\"red\", \n            linetype=\"dashed\", \n            alpha=0.56, lwd=1) +\n  geom_text(data = df %>% filter(N_total == max(N_total)),\n            aes(label = \"O(logn)\",\n                x = N_total + 0.5,\n                y = log(N_total) + 0.25,\n                color = \"red\")) +\n  guides(color = 'none')\n```\n\n::: {.cell-output-display}\n![](problem_set_files/figure-pdf/unnamed-chunk-4-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nNote that when we overlay the theoretical $O(log(n))$ function over the first figure, we see that network diameter remains largely bounded between 6 and 9 across all network sizes up to ~23,000 nodes, consistent with the small-world / six-degrees-of-separation phenomenon. The theoretical $log(n)$ curve provides a loose upper bound, and the observed diameters grow far more slowly than even that, which perhaps suggests that larger networks do not require substantially more hops to traverse.\n\nFor the second figure, we can associate a positive relationship between average distances between nodes and network size (largest component); this further reinforces the $O(log(n))$ growth rate, as distances between nodes continue to grow as we increase the overall size, but at a very slow rate (y-axis only spans from ~2.2-3.2). Note that the $O(log(n))$ relationship is defined for the diameter, which is the 'worst-case' scenario of the largest path in the network; the average-distance is more representative of the whole population.\n\n## (d) Facebook Diameter Today\n\n(d) Briefly discuss whether and why you think the diameter of Facebook has increased, stayed the same, or decreased relative to these values, since 2005. (Recall that Facebook now claims to have roughly $10^9$ accounts.)\n    \n    \n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nfb_avg_dist = mean(df$Mean_Distance)\nfb_avg_diam = mean(df$Diameter)\ntotal_network_2005 <- sum(df$N_total)\ndiam_dist_factor = round(fb_avg_diam/fb_avg_dist,2)\n```\n:::\n\n\nWe think the diameter of Facebook has likely *slightly* increased or even stayed the same as their network size has increased. If its diameter truly obeys such a $O(log(n))$ growth rate, then $log(10^9)$ should evaluate to $\\approx 20.7$; however, as the network grows larger, it is likelier that any individual (node) has more friends on the network and thereby is more well-connected. Thus, we would expected the average degree (number of friends) $\\gamma$ to increase in the network. Suppose that $\\gamma = 200$, (which feels like a reasonable assumption for a network that has grown to $n = 10^9$ over 20 years); then, we would evaluate $\\frac{ln10^9}{ln200} \\approx 3.9$. In our data, the diameter seems to be $\\approx$ 2.87x larger than our average distance (both averaged across all 85 networks). Thus, we could estimate the modern diameter of the entire Facebook network to be somewhere near $\\approx 11.2$. This is a surprisingly small increase in the diameter for a $\\approx$ 1282x total increase in the network size; although, one must consider the fact that this data consists of university networks, and as such they are likelier to be more clustered than the average community. \n\n## (e) Bonus: Large Data\n\n(e) (Bonus points) Can you redo exercise a) with facebook large dataset instead? What can you do to improve the runtime?\n\n*Hint*: The facebook small dataset, contains 85 .mat files. Each file is an edge list for a 2005 snapshot of a Facebook social network among university students and faculty within some university. You can download the dataset from the class website.\n\nNote that even though the `.mat` data objects were sparse matrices (which are memory efficient), these networks can explode in size quickly as the number of connections increase. A huge bottleneck in the first question was calculating average distances between nodes in a network. This is an $O(n^2)$ operation, as we need to calculate the distance between every node in a $(n \\times n)$ matrix, and thereby requires more and more computing power very quickly as we increase our network size and complexity (for only 100_000 observations, this is already an operation of $10^10$ calculations!). A strategy to improve performance would thereby be one where we **approximate distances** between nodes, rather than extracting *exact* values. For example, we may look at take a random sample of ~100 nodes and calculate average distances / find the max geodesic path for them, and use that value as an approximation of our true values. This strategy is well-justified, since we saw evidence from part (b-c) that distances/diameters don't seem to vary wildly amongst nodes, but rather cluster around ~2-3/6-9.\n\n# 2 Random Graph Models\n\nConsider the random graph $G(n, p)$ with average degree $c$.\n\n## (a) Triangles\n\n(a) Show that in the limit of large $n$ the expected number of triangles in the network is $\\frac{1}{6}c^3$\n\nIn other words, show that the number of triangles is constant, neither growing nor vanishing in the limit of large $n$.\n\n**Solution**: \n\nNote that the formula for expected number of triangles in a network with average degree of $c$ is found as ${n \\choose 3} p^3$, which can be rewritten as: \n\n$$\\frac{n!}{(n-3)! \\cdot 3!} = \\frac{1}{6} \\frac{n(n-1)(n-2) \\dots}{(n-3)(n-4) \\dots}$$\n\nWhich then simplifies into:\n\n$$\\frac{1}{6} n(n-1)(n-2)$$\n\nThus, we want to show that: \n\n$$\\lim_{n \\rightarrow \\infty} \\frac{1}{6} n(n-1)(n-2)\\cdot p^3  = \\frac{1}{6} c^3$$ \n\nTo do so, we must state the relationship of $c = (n-1)p$, where we will, for simplicity, rewrite this as $c \\approx np$ (since we are taking the limit to infinity, the difference between $n$ and $n-1$ is negligible and makes for smoother derivations). \n\nWe can then rewrite this (approximate) relationship as $n \\approx \\frac{c}{p}$, meaning that evaluating the limit as $n \\rightarrow \\infty$ is equivalent to taking $\\frac{c}{p} \\rightarrow \\infty$, which is true when $p \\rightarrow 0$. Thus, we can rewrite this limit expression as:\n\n$$\\lim_{p \\rightarrow 0} \\frac{1}{6} n(n-1)(n-2)\\cdot p^3$$\n\nNext, if we substitute in $n \\approx \\frac{c}{p}$, we can rewrite this expression as \n\n$$\\lim_{p \\rightarrow 0} \\frac{1}{6} \\frac{c}{p}(\\frac{c}{p}-1)(\\frac{c}{p}-2)\\cdot p^3$$ \n\nwhich, when we distribute the terms, are left with \n\n$$\\lim_{p \\rightarrow 0} \\frac{1}{6} \\left(\\frac{c^3}{p^3} - \\frac{3c^2}{p^2} + \\frac{2c}{p}\\right)\\cdot p^3$$ \n\nAfter distributing out the $p^3$ to our polynomial, we are left with: \n\n$$\\lim_{p \\rightarrow 0} \\frac{1}{6} \\left(c^3 - 3c^2p + 2cp^2\\right)$$ \n\nwhich, when evaluated at the limit, converges to:\n\n$$\\lim_{p \\rightarrow 0} \\frac{1}{6} \\left(c^3 - 3c^2(0) + 2c(0)^2\\right) = \\frac{1}{6} \\left(c^3\\right) \\\\ \\blacksquare$$\n\n## (b) Connected Triples\n\n(b) Show that the expected number of connected triples in the network is $\\frac{1}{2}nc^2$\n    \n**Solution:**\n\nNote that the expected number of connected triples in a network is given as $3 \\cdot {n \\choose 3} \\cdot p^2$, since for any group of three nodes, there are exactly three possible ways to form a triangle (A-B-C, A-C-B, & B-A-C). Thus, we can follow the same logic from part (a) and simplify this limit expression to become: \n\n$$\\lim_{p \\rightarrow 0} \\frac{1}{2} \\left(nc^2 - 3n^2p^2 + 2np^2\\right) $$\n\nWhich, when evaluated at the limit, simplifies to:\n\n$$\\lim_{p \\rightarrow 0} \\frac{1}{2} \\left(nc^2 - 3n^2(0)^2 + 2n(0)^2\\right) = \\frac{1}{2} \\left(nc^2\\right) \\\\ \\blacksquare$$\n\n## (c) Transitivity\n\n(c) Calculate transitivity $C$, as defined in the lecture notes, and confirm that it agrees for large $n$ with the value given in the slides (i.e. $C = \\frac{c}{n−1}$)\n    \n**Solution:**\n\nGiven $C \\propto \\frac{\\# \\text{expected number of triangles}}{\\# \\text{expected number of connected triples}}$: \n\nWe want to show that $C = \\frac{c}{n-1} \\rightarrow 0$; to do so, we plug in our results from (a) and (b), we can write: $$\\frac{\\frac{1}{6}c^3}{\\frac{1}{2}nc^2}$$ \n\nWhich, after simplifying, we get $$\\frac{c}{3n}$$ which, when evaluated at the limit as $n$ approaches infinity, we find that:\n\n$$lim_{n \\rightarrow \\infty} \\frac{c}{3n} = 0$$ \n\nThus, $C \\rightarrow 0$ as we increase the number of nodes in the network. In other words, as our network increases in size, we observe less and less triangles; this suggests that under an Erdos-Reny DGP, in a large enough network, it is unlikely for your friends to be friends with each other. This result makes sense from the random probability of being connected to a given node; in a real world setting, this is unlikely to hold as it does not allow for clustering amongst individuals.\n\n# 3 Custom Random Graph Program\n\nIdea: fix number of links ($n$) or fix prob ($p$), when n large enough these two will look alike. Since, when $n$ is small, it depends a lot on randomness ($p$)\n\n## (a0) Custom G(n,c) Model\n\nWrite a computer program in the language of your choice that generates a random graph drawn from the model $G(n, m)$ for given values of $n$ and the average degree $c = \\frac{2m}{n}$, and calculates the size of its largest component. Notice that this model is slightly different than the $G(n, p)$ model we saw in class.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngnm_graph = function(n, c, seed=1) {\n  set.seed(seed)\n  m = as.integer((c * n) / 2)\n  \n  # sample m random edges\n  edges = cbind(\n    sample(1:n, m, replace=TRUE),\n    sample(1:n, m, replace=TRUE)\n  )\n  \n  # remove self-loops\n  edges = edges[edges[,1] != edges[,2], ]\n  \n  g = make_graph(edges=as.vector(t(edges)), n=n, directed=FALSE)\n  return(vcount(largest_component(g)))\n}\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.python .cell-code  code-fold=\"true\" code-summary=\"function written in Python\"}\nimport numpy as np\nimport scipy.sparse as sp\n\ndef random_graph2(n: int, c: float):\n    \"\"\"Generates a Random Graph from a G(n,m) Model\"\"\"\n    network = sp.lil_matrix((n,n), dtype=int) # init sparse matrix\n    edges = set()                             # init unordered, no duplicates list to store unique pairs\n    m = int((c * n) / 2)                      # convert avg dist to num of edges\n    \n    while len(edges) < m:                     # empty: len(edges) init as 0: go until we have exactly m edges\n        i,j = np.random.randint(0,n,size=2)   # randomly gen 1 of n^2 possible 1D arrays\n\n        if i != j:                            # if not the same edge (removes self-loops):\n            edges.add((min(i,j), max(i,j)))   # add the edge to our list (len(edges) + 1)\n\n    for i,j in edges:                     # after we have our random list of m edges\n        network[i,j] = 1                  # assign upper triangle vals to 1\n        network[j,i] = 1                  # symmetric: same for lower triangle\n        \n    return network.tocsr()                # return as a csr for efficient operations\n```\n:::\n\n\n## (a) Largest Component\n\n(a) Use your program to find the size of the largest component in a random graph with $n =$ 1_000_000 and $c = 2ln2 = 1.3863 \\dots$ and compare your answer to the analytic prediction for the giant component of $G(n, p)$ with the same parameter values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn=1000000\nc= 2* log(2)\np = c / (n - 1)\nglue(\"G(n,m) largest component: {gnm_graph(n, c)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nG(n,m) largest component: 500304\n```\n\n\n:::\n\n```{.r .cell-code}\ng=sample_gnp(n,p)\nglue(\"G(n,p) largest component: {vcount(largest_component(g))}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nG(n,p) largest component: 501071\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.python .cell-code  code-fold=\"true\" code-summary=\"code written in Python\"}\nimport time\nimport igraph as ig\n\n# evaluate, store object\nstart = time.time()\nrandgraph = random_graph2(n=1_000_000, c=2*math.log(2)) # 11.4 sec\nprint(f\"done in {time.time() - start:.2f}s\")\n\ncx = randgraph.nonzero()  # returns (row_array, col_array) from csr directly;\n\ngraph = ig.Graph(\n    n=randgraph.shape[0],              \n    edges=list(zip(cx[0].tolist(),     # cx.row: array of source nodes\n                   cx[1].tolist())),   # cx.col: array of destination nodes\n    directed=False                        # need to make np.arrays() to lists() for igraph \n)                                         # zip() pairs the elements, converted to a list() object\n\n# largest component\nlargest = max(graph.connected_components(), # returns a list of lists -- each one represents a connected component\n              key=len)                      # get list of nodes that form the largest connection\nprint(f\"length of largest component in our network: {len(largest)}\")  # print the length of this node list\nigraph\n```\n:::\n\n\n## (b) Simulate & Plot Distributions\n\n(b) Do you understand why your answers agree? To make sense of this, create a plot that shows the distribution of m across different instances of $G(n, p)$. What happens to this distribution as $n \\rightarrow \\infty$?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc <- 2 * log(2)                                # average degree of all nodes in network\nns <- c(10, 100, 1000, 10000, 100000, 1000000) # different node sizes (n -> infty)\nreps <- 2000\n\n# simulate for each n\nresults <- lapply(ns, function(n) {\n  p <- c / (n - 1)\n  total_possible <- n * (n - 1) / 2       # total possible edge (upper triangle == symm matrix)\n  mean_m <- total_possible * p            # expected number of edges\n  \n  m_vals <- rbinom(n = reps,              # simulate random edge creation reps=2000 times; higher = converge\n                   size = total_possible, # total num edges randomly drawn from a bionmial dist \n                   prob = p)              # drawn with equal probabilities 'p'\n  \n  data.frame(\n    n = as.factor(paste0(\"n = \", format(n, big.mark=\"_\"))), # treat as factor to facet_wrap later on\n    rel_dev = (m_vals - mean_m) / mean_m  # deviation from the mean\n  )\n})\n\ndf <- bind_rows(results)                  # append simulation results into a df\n\ndf %>% \n  group_by(n) %>% \n  summarize(avg_dev = mean(rel_dev))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 x 2\n  n              avg_dev\n  <fct>            <dbl>\n1 n = 10      0.00361   \n2 n = 100     0.00104   \n3 n = 1_000   0.0000228 \n4 n = 10_000 -0.0000203 \n5 n = 1e+05  -0.00000620\n6 n = 1e+06  -0.0000538 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"plotting code\"}\nggplot(df, aes(x = rel_dev, fill = n)) +\n  geom_histogram(aes(y = after_stat(density)), bins = 40, \n                 color = \"white\", alpha = 0.8) +\n  facet_wrap(~n, scales = \"free\") +\n  labs(\n    title = \"Distribution of m in G(n,p)\", \n    subtitle = \"Relative Deviation from the Mean\",\n    x = \"(m - E[m]) / E[m]\",\n    y = \"Density\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"none\",\n        plot.title = element_text(hjust=0.5),\n        plot.subtitle = element_text(hjust=0.5))\n```\n\n::: {.cell-output-display}\n![](problem_set_files/figure-pdf/unnamed-chunk-11-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nObserving the graphs, we notice that the distribution noticeably gets tighter around the mean 0, meaning that non-zero deviations are statistically very unlikely at large enough $n$. This follows from $p=\\frac{c}{n−1}$ and the fact that the total number of possible edges is equivalent to the upper triangle of our symmetric adjacency matrix $\\frac{n(n-1)}{2}$. Thus, the expected number of edges of our network is found as (Total Possible Edges)(Probability of an Edge Forming) = $\\frac{n(n-1)}{2} \\cdot \\frac{c}{n−1} = \\frac{cn}{2}$. Since this grows linearly with n, the relative deviation from the mean vanishes for sufficiently large n; thus, the distribution for $G(n,p)$ and $G(n,m)$ should be asymptotically identical.\n\n## (c) G(n,m) == G(n,p)\n\n(c) Using the previous result and the fact that, as we saw in class, ⟨$m$⟩ $= \\frac{1}{2} n(n − 1)p$ for $G(n, p)$ random graphs, argue precisely why the two models agree for large values of $m$ and $n$.\n\nWe know that for the random graph model (because each of the $\\binom{n}{2}$ possible edges is included independently with probability $p$), $$m \\sim \\text{Bin}\\left(\\binom{n}{2},\\ p\\right)$$ with mean $\\binom{n}{2}p$ and variance $\\binom{n}{2}p(1-p)$. Thus, as $m \\rightarrow \\infty$, it should converge to its mean value; in other words, a random draw from the distribution of $G(n,p)$ should have $m \\approx \\frac{cn}{2}$, by the LLN ($\\bar{X}_n \\rightarrow \\mathbb{E}[X_n]$), which is the exact $m$ value you would plug into the $G(n,m)$ model. Thus, at large enough $n$ these graphs should be basically identical.\n    \nI.e. typical draw from $G(n,p)$ with $p = \\frac{c}{n-1}$ will have almost exactly $m = \\frac{cn}{2}$ edges as $n \\rightarrow \\infty$\n\n\n# 4. Preferential Attachment\n\nIn a 2009 paper, Mark Newman tests some features of the preferential attachment model we saw in class. In particular, he evaluates a network of citations among scientific papers on network sciences spanning ten years (June 1998 to June 2008) and documents the first mover advantage that is a standard feature of this model. Newman reproduces the following figure. In this exercise you are asked to replicate these figures for a different data set on citations among physics papers.\n\n![*Figure 1*:](C:/Users/T14/7Programming/R/class/networks/images/network_citations.png)\n\n## (a) Data \n\n(a) Use the citation graph from the e-print arXiv. You can download it here: [SNAP website](https://snap.stanford.edu/data/cit-HepPh.html). It covers all the citations within a dataset of 34,546 papers with 421,578 edges. If a paper i cites paper j, the graph contains a directed edge from i to j (if a paper cites, or is cited by, a paper outside the dataset, the graph does not contain any information about this). The data covers papers in the period from January 1993 to April 2003 (124 months). Notice that there are two files to download: one contains the edge-list and the other contains the publication date of papers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load the data\npaper_citation <- read_delim(\"data/cit-HepPh.txt.gz\", delim = \"\\t\", \n                              comment = \"#\", col_names = c(\"FromNodeId\", \"ToNodeId\"))\n\ndates_citation <- read_delim(\"data/cit-HepPh-dates.txt.gz\", delim = \"\\t\", \n                              comment = \"#\", col_names = c(\"FromNodeId\", \"ToNodeId\"))\n\n# Transform the dataset into a readable graph for the igraph library\ng_paper <- graph_from_data_frame(paper_citation, directed = TRUE)\ng_dates <- graph_from_data_frame(dates_citation, directed = TRUE)\n\n# Basic graph description \nvcount(g_paper) # number of nodes\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 34546\n```\n\n\n:::\n\n```{.r .cell-code}\necount(g_paper) # number of edges\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 421578\n```\n\n\n:::\n\n```{.r .cell-code}\nedge_density(g_paper)  # tells how full the network is (0 = empty, 1 = complete)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0003532604\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(degree(g_paper))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   1.00    7.00   15.00   24.41   31.00  846.00 \n```\n\n\n:::\n\n```{.r .cell-code}\nmean_distance(g_paper, directed = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 11.69297\n```\n\n\n:::\n\n```{.r .cell-code}\nreciprocity(g_paper)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.003117186\n```\n\n\n:::\n:::\n\n\nThe network consists of 34,546 nodes and 421,578 directed edges,\nindicating a relatively large graph in terms of actors and connections.\nThe edge density (0.00035) is extremely low, meaning that only a very\nsmall fraction of all possible ties are present. This suggests a highly\nsparse network, which is typical in large real-world systems such as\ncitation or collaboration networks.\n\nThe degree distribution shows substantial variation in connectivity.\nWhile the minimum degree is 1, the maximum reaches 846, and the mean\ndegree is 24.41. The median (15) being lower than the mean indicates a\nright-skewed distribution: most nodes have relatively few connections,\nwhile a small number of nodes are highly connected. This pattern is\ncharacteristic of heterogeneous or hub-dominated networks.\n\nThe average path length (11.69) indicates that, on average, about 12\nsteps are needed to move from one node to another along directed paths.\nGiven the size of the network, this suggests moderate reachability but\nnot a highly compact structure.\n\nFinally, the reciprocity value (0.0031) is extremely low, meaning that\nmutual connections (A → B and B → A) are very rare. This implies that\nrelationships in the network are largely asymmetric, which is typical\nfor hierarchical, citation, or information-flow networks rather than\nmutual social interaction networks.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Sanity check to know which direction (in or out) represents citations\ncat(\"Mean in-degree: \",  mean(degree(g_paper, mode = \"in\")),  \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean in-degree:  12.20338 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Mean out-degree: \", mean(degree(g_paper, mode = \"out\")), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean out-degree:  12.20338 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Var in-degree: \",  var(degree(g_paper, mode = \"in\")),  \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nVar in-degree:  641.723 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Var out-degree: \", var(degree(g_paper, mode = \"out\")), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nVar out-degree:  231.7846 \n```\n\n\n:::\n:::\n\n\nIn a citation network, according to Newman (2009), citations should follow a power law distribution, meaning that the \"in\" or \"out\" node direction that shows the highest variance, is the direction of citations, while the other will represent the references (bibliography) which should be more uniformly distributed. \n\n\n## (b) Panel a\n\n(b) Panel a) shows the how the complementary CDF looks linear in log-log scale. Recall this happens when the degree distribution follows a power-law. Notice that the figure shows a very good fit of the data to the theoretical prediction that we saw in class. Can you reproduce such a figure? Do you get as nice a fit? Notice that you will need to estimate m and the coefficient $\\gamma$ from the data. What values do you find? (*Hint*: as it says in the slides this can be done from simple linear regression).\n\nFrom the slides, the CCDF of a power law is\n$log(1−F(d))=log(\\frac{a}{1−γ})+(1−γ)log(d)$, therefore, if we fit a\nlinear regression (log-log), our beta would be estimated and it would\nrepresent $\\beta = 1-\\gamma$. Isolating, $\\gamma = 1-\\beta$.\n\nBecause of the preferential attachment of the network, $m$ is measured using the *Barabási-Albert (BA) model*. The idea from the BA model is that new nodes are more likely to connect to nodes that already have many connections (\"The rich get richer\"). The degree distribution from this model follows a power law: $P(k) ∼ k^{-3}$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compute the in-degree of every node (= number of citations each paper received)\ndeg <- degree(g_paper, mode = \"in\")\n\n# Compute the CCDF of the in-degree distribution: P(X >= k) for each k\ndd <- degree_distribution(g_paper, mode = \"in\", cumulative = TRUE)\n\n# dd is indexed starting at 1 but represents degree starting at 0, so we manually build the corresponding degree values\nk_vals <- 0:(length(dd) - 1)\n\n# Remove entries where CCDF = 0 (undefined in log scale) or degree = 0\n# (isolated nodes, meaning papers with no citations are not meaningful for power law)\nmask      <- dd > 0 & k_vals > 0\nk_plot    <- k_vals[mask]   \nccdf_plot <- dd[mask]       \n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"plotting code\"}\n# Build a data frame for ggplot using the same filtering logic\n# Note: dd is 1-indexed but represents degree 0, 1, 2, ... so dd[k_vals + 1] correctly accesses the CCDF value for each degree\ndf_full <- data.frame(\n  k = k_vals[k_vals > 0 & dd[k_vals + 1] > 0],\n  ccdf = dd[k_vals > 0 & dd[k_vals + 1] > 0]\n)\n\n# Plot the full CCDF on a log-log scale to visually inspect where the distribution becomes linear (i.e. where the power law kicks in) \n# Note: The power law only describes the tail, not the entire distribution. That is the reason why we want high degrees, because at low degrees, the distribution does not follow a power law. \n\nggplot(df_full, aes(x = k, y = ccdf)) +\n  geom_point(color = \"steelblue\", size = 1.5) +\n  scale_x_log10() +\n  scale_y_log10() +\n  annotation_logticks() +\n  labs(\n    title = \"Full CCDF to inspect where log-log linearity begins\",\n    x     = \"Degree k\",\n    y     = \"P(X ≥ k)\"\n  ) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](problem_set_files/figure-pdf/unnamed-chunk-15-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Set dmin based on visual inspection of the plot.\n# We only want to fit the regression where the CCDF is actually linear in log-log scale (the tail). The curved part at low degrees is due to finite-size effects and should be excluded.\ndmin <- 10\n\n# Keep only observations with a higher degree\nmask_tail <- k_plot >= dmin\nk_tail    <- k_plot[mask_tail]\nccdf_tail <- ccdf_plot[mask_tail]\n```\n:::\n\n\nHaving filtered the lower degrees, we proceed to fit a linear regression to get the $\\gamma$ and $m$ estimates. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit   <- lm(log(ccdf_tail) ~ log(k_tail))\nalpha <- coef(fit)[1]  # intercept\nbeta  <- coef(fit)[2]  # slope\n\ncat(\"Regression intercept (alpha):\", round(alpha, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRegression intercept (alpha): 7.968 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Regression slope (beta):     \", round(beta,  4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRegression slope (beta):      -2.725 \n```\n\n\n:::\n:::\n\n\nAlready explicitly mentioned before, $\\gamma = 1-\\beta$\n\nNote that $\\beta$ is negative, meaning gamma will be greater than 1 (theoretical BA $\\gamma = 3$)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngamma_est <- 1 - beta\ncat(\"\\nEstimated gamma:\", round(gamma_est, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nEstimated gamma: 3.725 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Theoretical gamma (BA model): 3\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTheoretical gamma (BA model): 3\n```\n\n\n:::\n:::\n\n\nTo recover the $m$ from the intercept we should keep in mind that $\\log(1-F(d)) = 2 \\log(m)-2\\log(d)$. Thus $\\alpha = 2\\log(m)$ and $m = e^{\\frac{\\alpha}{2}}$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_est_ccdf <- exp(alpha / 2)\ncat(\"\\nEstimated m (from CCDF intercept):\", round(m_est_ccdf, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nEstimated m (from CCDF intercept): 53.731 \n```\n\n\n:::\n:::\n\n\nEven though the plot might suggest to use dmin = 10, different values are also tries to check robustness of the estimators.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Try different values of dmin and compare gamma estimates and check if dmin was the best option\nfor (dmin_try in c(5, 10, 20, 50)) {\n  mask_try  <- k_plot >= dmin_try\n  fit_try   <- lm(log(ccdf_plot[mask_try]) ~ log(k_plot[mask_try]))\n  gamma_try <- 1 - coef(fit_try)[2]\n  m_try     <- exp(coef(fit_try)[1] / 2)\n  cat(sprintf(\"dmin = %3d  →  gamma = %.3f,  m = %.3f\\n\",\n              dmin_try, gamma_try, m_try))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ndmin =   5  →  gamma = 3.627,  m = 40.055\ndmin =  10  →  gamma = 3.725,  m = 53.731\ndmin =  20  →  gamma = 3.855,  m = 79.460\ndmin =  50  →  gamma = 4.083,  m = 159.608\n```\n\n\n:::\n:::\n\n\nThe output suggests the estimates are not very stable as the $\\gamma$ increases from 3.6 to 4.1 and $m$ grows substantially. \n\nThe theoretical BA $\\gamma$ prediction is 3 but the estimates are all above 3 and grow as dmin increases. Hence, the results suggest that the tail of the distribution is steeper than a pure BA power law, which is not a worrying result because of the type of data we are working with. Real citation networks might not perfectly align with the BA model.\n\nFinally, the plot reproduction: \n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"plotting code\"}\n# Data frames for ggplot\ndf_plot <- data.frame(k = k_plot, ccdf = ccdf_plot)\nk_seq   <- seq(min(k_plot), max(k_plot), length.out = 200)\n  df_fit  <- data.frame(k = k_seq, ccdf = exp(alpha + beta * log(k_seq)))\n\nk_seq  <- seq(dmin, max(k_tail), length.out = 500)\ndf_fit <- data.frame(k    = k_seq,\n                     ccdf = exp(alpha + beta * log(k_seq)))\n\nggplot() +\n  geom_point(data = df_plot, aes(x = k, y = ccdf),\n             color = \"steelblue\", size = 1.5) +\n  geom_line(data = df_fit, aes(x = k, y = ccdf),\n            color = \"red\", linewidth = 1) +\n  scale_x_log10() +\n  scale_y_log10() +\n  annotation_logticks() +\n  labs(\n    title    = \"CCDF of in-degree (log-log scale)\",\n    subtitle = paste0(\"γ ≈ \", round(gamma_est, 2),\n                      \",  m ≈ \", round(m_est_ccdf, 2),\n                      \"  (fitted for d ≥ \", dmin, \")\"),\n    x = \"Degree k\",\n    y = \"P(X ≥ k)\"\n  ) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](problem_set_files/figure-pdf/unnamed-chunk-21-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nThe degree distribution from the data does not fit the linear log-log line as accurately as in the Newman paper but it quite approximates to that relation. \n\n\n## (c) Panel b\n\n(c) Panel b) shows that early publications have a larger mean number of citations than later publications. The model predicts that the average number of citations a paper receives is decreasing in the paper’s publication date (i.e. becomes arbitrarily large as $i \\rightarrow 0$, which in Newman this means $t \\rightarrow 0$). The black line in the figure is essentially plotting this theoretical prediction from the model, using the value of $m$ estimated in part previous section. Can you reproduce the figure?\n\nFirst of all, we need the theoretical prediction (black line) of average citations as a function of publication time, so that we can compare it to the data from real citations.\n\nFrom the BA model in the slides, the expected degree of a node added at time i in a network of size N is: \n\n$<k(t)> = m(\\sqrt(\\frac{1}{t})-1)$ where $t = \\frac{i}{N}$ is the normalized publication time.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nN <- vcount(g_paper)\nt_vals <- (1:N) / N\n```\n:::\n\n\nFrom the data, we compute the empirical average citations per time bin to get all the required information to graphically replicate panel b)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Bin papers into time intervals and compute mean in-degree per bin\nn_bins <- 50\nbreaks <- seq(0, 1, length.out = n_bins + 1)\nbin_mid <- (breaks[-1] + breaks[-(n_bins + 1)]) / 2  # midpoint of each bin\nbin_index <- cut(t_vals, breaks = breaks, include.lowest = TRUE)\n\navg_citations <- tapply(deg, bin_index, mean)\n\ndf_empirical <- data.frame(\n  t = bin_mid,\n  avgk = as.numeric(avg_citations)\n)\n```\n:::\n\n\nAs mentioned before, to have a comparison baseline from the empiric we need the theoretical prediction. For that purpose, the estimated $m$ in section b) is used. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nt_seq <- seq(0.01, 1, length.out = 500)  # avoid t=0 (diverges to infinity)\ndf_theory <- data.frame(\n  t = t_seq,\n  avgk = m_est_ccdf * (1 / sqrt(t_seq) - 1)\n)\n```\n:::\n\n\nGrouping the results above into a plot we get the replication of panel b) for the physics citations dataset. \n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"plotting code\"}\nggplot() +\n  geom_bar(data  = df_empirical, aes(x = t, y = avgk),\n           stat  = \"identity\", fill = \"brown\",\n           color = \"black\", width = 1 / n_bins, alpha = 0.8) +\n  geom_line(data = df_theory, aes(x = t, y = avgk),\n            color = \"black\", linewidth = 1) +\n  ylim(0, 40) +\n  labs(\n    title    = \"Average citations vs publication time\",\n    subtitle = paste0(\"Theoretical curve uses m = \", round(m_est_ccdf, 2)),\n    x        = \"Time t\",\n    y        = \"Average citations <k(t)>\"\n  ) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](problem_set_files/figure-pdf/unnamed-chunk-25-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nThe plot can be used as a double verification on the $m$ estimated. If the bars from the graph above do not quite match the theoretical line it indicates that the network deviates from a standard BA model, common with real citation data. \n\nThe peak at t almost 1 shows that, although older papers are more cited than new ones, there is a group of recent investigations that became quite famous within the researchers. Because data on physics papers during only 10 years represents little of the total amount of physics research over the years, it make quite sense that the bars do not perfectly align with the theoretical line. Moreover, physics is an old discipline, which might indicate that a 10 year period is not representative of the whole citation network distribution. Yet, the peak at the end of the period indicates that around 2002-2003, there was some big advances in the field that created relevant highly cited papers. \n\n\n## (d) Panels c, d, e\n\n(d) Last panels (c) to (e) show the first-mover advantage by showing that a paper with more citations at the end of the sample (i.e. panel (e)) have a higher probability of being published at an earlier time (i.e. has more mass for lower t) than a paper with less citations (i.e. panel (c)). Can you replicate these graphs with your data?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntercile_breaks <- quantile(deg, probs = c(0, 1/3, 2/3, 1))\n\ngroup <- cut(deg,\n             breaks         = tercile_breaks,\n             labels         = c(\"(c) Low citations\",\n                                \"(d) Medium citations\",\n                                \"(e) High citations\"),\n             include.lowest = TRUE)\n\ndf_all <- data.frame(\n  t     = t_vals,\n  deg   = deg,\n  group = group\n)\n```\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"plotting code\"}\nggplot(df_all, aes(x = t)) +\n  geom_histogram(aes(y = after_stat(density)),\n                 bins  = 20,\n                 fill  = \"brown\",\n                 color = \"black\",\n                 alpha = 0.8) +\n  geom_density(color     = \"black\",\n               linewidth = 1,\n               adjust    = 1.5) +\n  facet_wrap(~ group, ncol = 3) +\n  scale_x_continuous(limits = c(0, 1), breaks = c(0, 0.5, 1)) +\n  labs(\n    title = \"First-mover advantage: distribution of publication times by citation group\",\n    x     = \"Time t\",\n    y     = \"Probability density\"\n  ) +\n  theme_bw() +\n  theme(strip.text = element_text(size = 10))\n```\n\n::: {.cell-output-display}\n![](problem_set_files/figure-pdf/unnamed-chunk-27-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nAccording to Newman's hypothesis and proof, older papers should have more citations than younger publications. Figure c), which represents the \"low citations\" group, has its distribution skewed towards recent time periods (right) identifying late published (new) papers as lower cited. \n\nThe medium citations distribution is roughly bell-shaped and centered around t = 0.5 as it should. \n\nThe last group brings together the highly cited papers and, although the distribution is left-skewed as Newman predicted, there is a discrepancy between Newman's results and those obtained from the dataset used in this assignment. This discrepancy is evident in the significant bins at high t values, which, as before, indicate that most highly cited papers were published earlier. However, there are also some more recently published research articles that have gained considerable importance within the research community.\n\n\n## (e) First-Mover Advantage\n\n(e) Newman mentions that \"the first-mover advantage is sizable: the first 10% of papers in this example received an average of 101 citations each, while the second 10%-published only little later-received just 26. The most recent 10% of papers in the data set received a miserable 0.08 citations each, meaning that most of them have never been cited all.\" Can you provide a similar statement for your data?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Divide papers into deciles by publication time\ndeciles <- cut(t_vals,\n               breaks         = quantile(t_vals, probs = seq(0, 1, by = 0.1)),\n               labels         = paste0(seq(10, 100, by = 10), \"%\"),\n               include.lowest = TRUE)\n\ndf_deciles <- data.frame(\n  t         = t_vals,\n  citations = deg,\n  decile    = deciles\n)\n\n# Average citations per decile\navg_by_decile <- tapply(deg, deciles, mean)\n\n# Print the statement\ncat(\"First-mover advantage by decile:\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFirst-mover advantage by decile:\n```\n\n\n:::\n\n```{.r .cell-code}\nfor (i in 1:10) {\n  cat(sprintf(\"  %s earliest papers: %.2f average citations\\n\",\n              names(avg_by_decile)[i],\n              avg_by_decile[i]))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  10% earliest papers: 43.27 average citations\n  20% earliest papers: 23.88 average citations\n  30% earliest papers: 16.23 average citations\n  40% earliest papers: 10.65 average citations\n  50% earliest papers: 7.28 average citations\n  60% earliest papers: 4.98 average citations\n  70% earliest papers: 3.13 average citations\n  80% earliest papers: 1.71 average citations\n  90% earliest papers: 0.63 average citations\n  100% earliest papers: 10.28 average citations\n```\n\n\n:::\n:::\n\n\nSummarizing the results and to provide an equivalent statement to that of Newman: The first 10% of papers received an average of 43.27 citations each. The second 10% of papers received an average of 23.88 citations each. The most recent 10% of papers received an average of 10.28 citations each, meaning 27.6% of them have never been cited at all.\n\nAgain, we find the citation outliers in the recent period analysed. \n\n## (f) Bonus\n\n(f) (Bonus points) Recall that in the slides we had $d_i(t) = m(\\frac{t}{i})^{\\frac{1}{2}}$. This is a particular case of the more general form of equation (16) in Newman. Can you prove it? Note that class notation doesn’t match paper notation, you will need to work around that.\n\n\n::: {.cell}\n\n:::\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}