{
  "hash": "0e2fd4c5875646b07301834c53ed71a7",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Problem Set 3\"\nauthor: \"Xénia Alemany, Michael Fehl\"\ndesc: \"Cascades, Seeding, Routing, and Opinion Dynamics\"\ndate: \"March 10, 2026\"\nimage: \"/images/ps03_email.png\"\nformat:\n  html:\n    embed-resources: true\n  pdf:\n    toc: true\n    number-sections: true\n    geometry: margin=1in\n    \nexecute:\n  error: true\n  cache: true\n  \nknitr:\n  opts_chunk:\n    message: false\n    warning: false\n    crop: false\n---\n\nLoad the required libraries:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(igraph)\nlibrary(ggplot2)\nlibrary(tidyr)\nlibrary(tidyverse)\n```\n:::\n\n\n# Cascades and Network Structure\n\n## Exercise 1: Impact of Community Structure on Disease Dynamics\n\nIn this question, we explore via numerical simulation the impact that community structure has on the dynamics of disease using the \"planted partition\" model.\n\n### (a) Visualizing Community Strength\n\nGenerate and create simple visualizations of three graphs using the following parameters: - **Population size (**$n$): 100 - **Number of communities (**$c$): 2 - **Average degree (**$d$): 10 - **Community strength (**$\\epsilon$): $\\{0, 4, 8\\}$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Basic parameters for the networks: \nn <- 100 # population size of the networks\nc <- 2 # number of communities\nd <- 10 # average degree\nepsilons <- c(0,4,8) # community strengths\n\n# We created a function to generate the graphs and compute the p and q\ngenerate_planted_partition <- function(n, c, d, epsilon) {\n  # Based on the mapping mentioned in the slides:\n  p <- (d + epsilon) / n\n  q <- (d - epsilon) / n\n  \n  # Define the probability matrix for the Stochastic Block Model\n  # Diagonal elements are 'p' (within), off-diagonals are 'q' (across)\n  pref_matrix <- matrix(q, nrow = c, ncol = c)\n  diag(pref_matrix) <- p\n  \n  # Generate the graph using the Stochastic Block Model\n  g <- sample_sbm(n, pref_matrix, block.sizes = rep(n/c, c), directed = FALSE)\n  return(g)\n}\n\n# Generate and plot the three graphs\npar(mfrow = c(1, 3), mar = c(1, 1, 3, 1)) # Layout for 3 plots\n\nfor (eps in epsilons) {\n  set.seed(42) # For reproducibility\n  g <- generate_planted_partition(n, c, d, eps)\n  \n  # Assign colors based on community (first 50 in group 1, next 50 in group 2)\n  V(g)$color <- c(rep(\"skyblue\", n/2), rep(\"orange\", n/2))\n  \n  plot(g, \n       vertex.label = NA, \n       vertex.size = 7, \n       layout = layout_with_fr(g), \n       main = paste(\"Epsilon =\", eps))\n}\n```\n\n::: {.cell-output-display}\n![](PS3_networks_files/figure-pdf/unnamed-chunk-2-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n**Task:** Comment on the strength of the community structure each of these graphs exhibits, noting how $\\epsilon$ maps into the probabilities $p$ (within-group) and $q$ (across-group).\n\nAfter plotting the graphs we clearly see the differences described in class.\n\n-   $\\epsilon = 0:$ represents a standard ER random graph where $p = q$ meaning there is no distinguishable community structure. This theoretical framework can clearly be seen in the first plot where the communities cannot be distinguished from one another.\n\n-   $\\epsilon = 4:$ represents a graph where the within-group probability increases while the across-group probability decreases. Consistently, the graph visualization shows that we begin to see distinct clusters forming.\n\n-   $\\epsilon = 8:$ represents a strong community structure. On this setting nodes are much more likely to connect to others within their own group rather than to the other community. This characteristic results in a much more clearly separated visual clusters.\n\nIf we were to continue increasing $\\epsilon$ until it equalized to d, then $q = 0$ and we would have two completely disconnected communities.\n\n### (b) Independent Cascade Model Simulation\n\nUsing a simple SI spreading process where the transmission probability $p$ is constant: - **Parameters:** $n=1000$, $d=8$, and $\\epsilon=0$. - **Simulation:** Measure the average epidemic size $\\langle s/n \\rangle$ and average epidemic length $\\langle l \\rangle$ as a function of $p \\in [0, 1]$. - **Requirement:** Average the measured $s$ and $l$ over multiple draws to ensure smooth functions. Vary $p$ slowly enough to capture high resolution in regions where the size or length changes quickly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Setup Parameters again\nn <- 1000\nd <- 8\nepsilon <- 0 # ER random graph model\n\n#Function to simulate one SI Epidemic\nsimulate_si_ic <- function(graph, p) {\n  n <- igraph::vcount(graph)\n  adj <- igraph::as_adj_list(graph)\n  \n  states <- rep(FALSE, n)\n  seed <- sample(1:n, 1)\n  states[seed] <- TRUE\n  newly_infected <- seed\n  t <- 1\n  \n  while (length(newly_infected) > 0) {\n    next_wave <- c()\n    for (u in newly_infected) {\n      neighbors <- as.integer(adj[[u]])\n      susceptible <- neighbors[!states[neighbors]]\n      if (length(susceptible) > 0) {\n        hits <- susceptible[runif(length(susceptible)) < p]\n        states[hits] <- TRUE\n        next_wave <- c(next_wave, hits)\n      }\n    }\n    newly_infected <- unique(next_wave)\n    if (length(newly_infected) > 0) t <- t + 1\n  }\n  \n  c(size = sum(states) / n, length = t)\n}\n\n# Denser p grid near the critical threshold (~1/d = 0.125)\np_values <- sort(unique(c(\n  seq(0,    0.05, by = 0.005),\n  seq(0.05, 0.35, by = 0.008),  # dense near critical point\n  seq(0.35, 1.0,  by = 0.05)\n)))\n\nresults <- data.frame()\n\nfor (p_trans in p_values) {\n  n_sims <- ifelse(p_trans < 0.35, 300, 80)\n  # Regenerate network on every replication (both sources of randomness)\n  temp_results <- replicate(n_sims, {\n    g <- generate_planted_partition(n = 1000, c = 2, d = 8, epsilon = 0)\n    simulate_si_ic(g, p_trans)\n  })\n  \n  results <- rbind(results, data.frame(\n    p      = p_trans,\n    size   = mean(temp_results[\"size\",   ]),\n    length = mean(temp_results[\"length\", ])\n  ))\n  \n  cat(\"p =\", round(p_trans, 3), \"done\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\np = 0 done\np = 0.005 done\np = 0.01 done\np = 0.015 done\np = 0.02 done\np = 0.025 done\np = 0.03 done\np = 0.035 done\np = 0.04 done\np = 0.045 done\np = 0.05 done\np = 0.058 done\np = 0.066 done\np = 0.074 done\np = 0.082 done\np = 0.09 done\np = 0.098 done\np = 0.106 done\np = 0.114 done\np = 0.122 done\np = 0.13 done\np = 0.138 done\np = 0.146 done\np = 0.154 done\np = 0.162 done\np = 0.17 done\np = 0.178 done\np = 0.186 done\np = 0.194 done\np = 0.202 done\np = 0.21 done\np = 0.218 done\np = 0.226 done\np = 0.234 done\np = 0.242 done\np = 0.25 done\np = 0.258 done\np = 0.266 done\np = 0.274 done\np = 0.282 done\np = 0.29 done\np = 0.298 done\np = 0.306 done\np = 0.314 done\np = 0.322 done\np = 0.33 done\np = 0.338 done\np = 0.346 done\np = 0.35 done\np = 0.4 done\np = 0.45 done\np = 0.5 done\np = 0.55 done\np = 0.6 done\np = 0.65 done\np = 0.7 done\np = 0.75 done\np = 0.8 done\np = 0.85 done\np = 0.9 done\np = 0.95 done\np = 1 done\n```\n\n\n:::\n\n```{.r .cell-code}\n# Epidemic Size Plot\nggplot(results, aes(x = p, y = size)) + \n  geom_line(color = \"blue\", size = 1) + \n  labs(title = \"Average Epidemic Size <s/n>\", x = \"Transmission Probability (p)\", y = \"Fraction of Nodes Infected\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](PS3_networks_files/figure-pdf/unnamed-chunk-3-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n# Epidemic Length Plot\nggplot(results, aes(x = p, y = length)) + \n  geom_line(color = \"red\", size = 1) + \n  labs(title = \"Average Epidemic Length <l>\", x = \"Transmission Probability (p)\", y = \"Time Steps\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](PS3_networks_files/figure-pdf/unnamed-chunk-3-2.pdf){fig-pos='H'}\n:::\n:::\n\n\n**Discussion:**\n\n1.  Comment on the qualitative behavior of these relationships relative to $p$.\n\nAs we saw in class, for low values of $p$, the infection dies out quickly because it only affects a tiny fraction of the whole network. As $p$ crosses a certain threshold, the magnitude of the infection jumps significantly toward 1 meaning all the network population is being infected.\n\nThe length of the epidemic typically exhibits a non-monotonic \"peaked\" behavior meaning that for low values of $p$ the length of the epidemic is short because the infection fails to spread and the disease gets 'eradicated' almost immediately. Yet, when we reach a certain $p$ threshold, the length of the epidemic hits its maximum, meaning that the spread is high enough for contagion to continue occurring as time goes by but it is not too high for the epidemic to be spread to all the nodes within a little period of time. Therefore, when $p$ is high that means that the spread is really fast and consequently, the length is shorter.\n\n2.  Is there a critical value of $p$ where a phase transition occurs?\n\nYes, as mentioned earlier, there is a critical value of $p$ when phase transition occurs. This phenomenon can be validated by the plots in this section. For a random network ($\\epsilon = 0$) as the one we are using in this section, the theoretical epidemic threshold is approximately $p \\approx \\frac{1}{d}$. Given that the average degree in this setting is 8, the theoretical threshold should be $p \\approx 0.125$ which is approximately what we observe in the graphs computed.\n\n### (c) Community Structure and Epidemic Size\n\nInvestigate whether the strength of community structure enhances, limits, or has no effect on epidemic size using $n=200$ and $d=8$.\n\nThe code calculates within-group probability $p = (d+\\epsilon)/n$ and across-group probability $q = (d-\\epsilon)/n$\n\nBecause we are working with the same average degree d, we would have the same $p$ theoretical value.\n\n**Task:**\n\n-   Characterize how $\\epsilon \\in [0, 2c]$ impacts epidemic size $s/n$ and/or length $l$ using clear figures.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Parameters\nn <- 200\nd <- 8\nc <- 2\nn_sims <- 100\np_values <- sort(unique(c(\n  seq(0, 0.05, by = 0.005),\n  seq(0.05, 0.35, by = 0.01),\n  seq(0.35, 1.0, by = 0.05)\n)))\nepsilon_values <- c(0, 2, 4)\n\nall_results <- data.frame()\n\nfor (eps in epsilon_values) {\n  for (p_trans in p_values) {\n    sims <- replicate(n_sims, {\n      p_in  <- (d + eps) / n\n      p_out <- (d - eps) / n\n      pref_matrix <- matrix(p_out, nrow = c, ncol = c)\n      diag(pref_matrix) <- p_in\n      g <- sample_sbm(n, pref_matrix, block.sizes = rep(n/c, c))\n      simulate_si_ic(g, p_trans)\n    })\n    all_results <- rbind(all_results, data.frame(\n      p       = p_trans,\n      epsilon = as.factor(eps),\n      size    = mean(sims[\"size\",   ]),\n      length  = mean(sims[\"length\", ])\n    ))\n  }\n}\n\nggplot(all_results, aes(x = p, y = size, color = epsilon)) +\n  geom_line(size = 1) +\n  labs(title = \"Epidemic Size vs. Community Strength\",\n       x = \"Transmission Probability (p)\", y = \"s/n\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](PS3_networks_files/figure-pdf/unnamed-chunk-4-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nggplot(all_results, aes(x = p, y = length, color = epsilon)) +\n  geom_line(size = 1) +\n  labs(title = \"Epidemic Length vs. Community Strength\",\n       x = \"Transmission Probability (p)\", y = \"Time Steps (l)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](PS3_networks_files/figure-pdf/unnamed-chunk-4-2.pdf){fig-pos='H'}\n:::\n:::\n\n\n-   Discuss the qualitative shape of these functions compared to your results in part (1b).\n\nTheoretically, as epsilon increases the communities become more isolated from each other which introduces friction to the system. The theoretical $p$ for the entire network shifts to the right (increases) because now the infection needs higher transmission probability to successfully jump across groups.\n\nAgainst theory we show that as epsilon increases, $p$ is not necessarily moved to the left and the length of the epidemic is also not peaking after. The plausible explanation found for those results is due to another force affecting the networks as we increase the within-group connections. When epsilon increases, nodes from a group are more connected between them but less connected with other groups. In our setting, the increase of node links within a community counteracts the fact that is should be more difficult for the disease to spread to the other group within the network, concluding on pretty similar graphs like the ones in part b.\n\n-   Provide a brief intuitive explanation for why community structure strength does or does not impact the shape of the epidemic.\n\nIn our context, community strength does not impact the shape of the epidemic but maybe it would for higher epsilon. The graphs below also include higher epsilons to understand the spread pattern when the groups are even stronger. The results follow the idea that the more clustered the groups are and consequently, the more isolated are from one another, the force that shape the infection spread change and it reaches a point where only half of the population is being infected because we reach the critical partition where q goes to 0 and the groups are not connected anymore.\n\n------------------------------------------------------------------------\n\n# Optimal Seeding\n\n## Exercise 2: Diffusion and Seed Optimization\n\nThis exercise simulates diffusion models to find optimal seeds using a real-world network dataset.\n\n### (a) Technology Diffusion Simulation\n\nFor $\\lambda=1$ and $\\lambda=2$, conduct technology diffusion simulations where each individual draws an adoption threshold $\\tau_i$ from a normal distribution $\\mathbb{N}(\\lambda, 0.5)$, truncated to be strictly positive.\n\n-   **Mechanism:** A node becomes informed in the next period if she is connected to at least $\\tau_i$ informed individuals.\n-   **Duration:** Run the model for four periods.\n-   **Metric:** Simulate the model 60 times for each potential pair of seeds to create a measure of the average information rate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nedge_data <- read.table(gzfile(\"email-Eu-core.txt.gz\"), header = FALSE) # load the data\n\n# Add 1 to convert from 0-indexed to 1-indexed\nedge_data <- edge_data + 1\n\n# Convert to graph\ng_full <- graph_from_edgelist(as.matrix(edge_data), directed = FALSE) #assumed undirected to simplify\ng_full <- simplify(g_full) #simplify the network \n\n# Keep largest connected component\ncomponents <- components(g_full)\nlargest_id <- which.max(components$csize)\ng <- induced_subgraph(g_full, which(components$membership == largest_id))\n\ncat(\"Nodes:\", vcount(g), \"| Edges:\", ecount(g), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNodes: 986 | Edges: 25552 \n```\n\n\n:::\n\n```{.r .cell-code}\nplot(g, vertex.size = 3, vertex.label = NA, \n     main = \"Email EU Core Network\")\n```\n\n::: {.cell-output-display}\n![](PS3_networks_files/figure-pdf/unnamed-chunk-5-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Threshold diffusion simulation \n# tau_i ~ truncated Normal(lambda, 0.5) --> strictly positive\n# A node adopts when #adopted_neighbors >= tau_i\n# Run for 4 periods\n# seeds start as adopted at t=0\n\nsimulate_diffusion <- function(g, seeds, lambda, n_periods = 4) {\n    n   <- vcount(g)\n  adj <- as_adj_list(g, mode = \"all\")   # neighbor list (undirected)\n  \n  # Draw truncated Normal thresholds (strictly positive)\n  repeat {\n    tau <- round(rnorm(n, mean = lambda, sd = 0.5))\n    if (all(tau >= 1)) break\n    tau[tau < 1] <- 1   # truncate to be strictly positive\n  }\n  \n  adopted <- rep(FALSE, n)\n  adopted[seeds] <- TRUE\n  \n  for (t in 1:n_periods) {\n    newly <- which(!adopted & \n                   sapply(1:n, function(i) sum(adopted[as.integer(adj[[i]])]) >= tau[i]))\n    adopted[newly] <- TRUE\n  }\n  \n  return(sum(adopted) / n)   # information rate\n}\n```\n:::\n\n\nThe simulation that is going to be generated thanks to the function above captures adoption through peer pressure. Truncating the normal distribution ensures the thresholds remain physically meaningful (\\> 0). Running the code for 4 periods allows us to see the initial cascade effect without having to wait for everyone to adopt. The 60 replications per pair average out the threshold randomness.\n\n### (b) Optimal Seed Identification\n\nIdentify and provide the identity of the optimal pair of seeds for both $\\lambda=1$ and $\\lambda=2$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Precompute adjacency list ONCE outside to speed up the code. \nadj_precomp <- as_adj_list(g, mode = \"all\")\nn           <- vcount(g)\n\n# Fix: handle case where vertex names are NULL after subgraph extraction\nnode_ids <- if (is.null(V(g)$name)) as.character(1:vcount(g)) else V(g)$name\n\n# Faster diffusion using precomputed adj\nsimulate_diffusion_fast <- function(seeds, lambda, n_periods = 4) {\n  tau     <- pmax(1L, round(rnorm(n, mean = lambda, sd = 0.5)))\n  adopted <- rep(FALSE, n)\n  adopted[seeds] <- TRUE\n  \n  for (t in 1:n_periods) {\n    counts <- sapply(1:n, function(i) sum(adopted[as.integer(adj_precomp[[i]])]))\n    newly  <- which(!adopted & counts >= tau)\n    if (length(newly) == 0) break\n    adopted[newly] <- TRUE\n  }\n  sum(adopted) / n\n}\n\nrun_optimal_seeding <- function(lambda) {\n  cat(\"\\nRunning lambda =\", lambda, \"...\\n\")\n  \n  deg <- degree(g, mode = \"all\")\n  \n  # Stage 1: quick screen with top 25 nodes, 20 reps\n  top_k      <- 25\n  n_mc_quick <- 20\n  candidates <- order(deg, decreasing = TRUE)[1:top_k]\n  pairs      <- combn(candidates, 2)\n  \n  rates <- apply(pairs, 2, function(seeds)\n    mean(replicate(n_mc_quick, simulate_diffusion_fast(seeds, lambda)))\n  )\n  \n  # Stage 2: refine top 10 pairs with full 60 reps\n  top_pairs  <- order(rates, decreasing = TRUE)[1:10]\n  rates_full <- sapply(top_pairs, function(j)\n    mean(replicate(60, simulate_diffusion_fast(pairs[, j], lambda)))\n  )\n  \n  best_j    <- top_pairs[which.max(rates_full)]\n  best_pair <- pairs[, best_j]\n  best_rate <- max(rates_full)\n  \n  # Report both internal index and original node ID\n  cat(\"Optimal seeds (indices):\", best_pair, \"\\n\")\n  cat(\"Optimal seeds (node IDs):\", node_ids[best_pair], \"\\n\")\n  cat(\"Average information rate:\", round(best_rate, 4), \"\\n\")\n  \n  list(best_pair  = best_pair, \n       best_ids   = node_ids[best_pair], \n       best_rate  = best_rate)\n}\n\nset.seed(42)\nres_lambda1 <- run_optimal_seeding(lambda = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nRunning lambda = 1 ...\nOptimal seeds (indices): 63 130 \nOptimal seeds (node IDs): 63 130 \nAverage information rate: 0.9877 \n```\n\n\n:::\n\n```{.r .cell-code}\nres_lambda2 <- run_optimal_seeding(lambda = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nRunning lambda = 2 ...\nOptimal seeds (indices): 161 167 \nOptimal seeds (node IDs): 161 167 \nAverage information rate: 0.9244 \n```\n\n\n:::\n:::\n\n\nWith a threshold of 1, a node adopts as soon as any single neighbor has adopted. The diffusion process is highly permissive, so nearly 98.6% of the network becomes informed within 4 periods regardless of seed choice. Nodes 161 and 212 are the best pair under this setting.\n\nWith a threshold of 2, adoption requires at least two informed neighbours simultaneously. This is a much more demanding condition and the information rate drops to 91.3%, which will be the percentage of the network informed after the four periods. The optimal seeds shift to nodes 83 and 421. Under stricter thresholds, the best seeds are not necessarily the highest-degree nodes but rather nodes that are well-positioned to create overlapping neighbourhoods, so that they share many common neighbours.\n\nThe drop of the information rate illustrates the friction created by a higher threshold as even with the best possible pair of seed in $\\lambda = 2$, almost a 9% of the network still is not adopting the technology after 4 periods.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Report optimal pairs\ncat(\"\\n── λ = 1 ──\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n── λ = 1 ──\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Optimal seeds:\", node_ids[res_lambda1$best_pair], \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOptimal seeds: 63 130 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Average information rate:\", round(res_lambda1$best_rate, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAverage information rate: 0.9877 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n── λ = 2 ──\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n── λ = 2 ──\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Optimal seeds:\", node_ids[res_lambda2$best_pair], \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOptimal seeds: 161 167 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Average information rate:\", round(res_lambda2$best_rate, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAverage information rate: 0.9244 \n```\n\n\n:::\n:::\n\n\nEvaluating all the pairs (around 500.000) is computationally really demanding, so the code pre-screens the top 50 nodes by degree and searches all (50 choose 2) = 1.225 pairs among them. \\### (c) Monte Carlo Comparison\n\nRun the same Monte Carlo simulation using randomly chosen seeds. Compare the rates of information diffusion with the optimal seeds identified in part (a) and discuss your findings.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compare with random seeds\nn_random_trials <- 50 \nn_mc_random     <- 20   # 60 → 20 reps per random pair\n\ncompare_seeds <- function(lambda, optimal_rate) {\n  random_rates <- replicate(n_random_trials, {\n    seeds <- sample(1:n, 2)\n    mean(replicate(n_mc_random, simulate_diffusion_fast(seeds, lambda)))\n  })\n  \n  cat(\"\\n── λ =\", lambda, \"──\\n\")\n  cat(\"Optimal seed rate:     \", round(optimal_rate,        4), \"\\n\")\n  cat(\"Random seeds mean rate:\", round(mean(random_rates),  4), \"\\n\")\n  cat(\"Random seeds max rate: \", round(max(random_rates),   4), \"\\n\")\n  \n  data.frame(lambda = lambda, rate = random_rates)\n}\n\nrand1 <- compare_seeds(1, res_lambda1$best_rate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n── λ = 1 ──\nOptimal seed rate:      0.9877 \nRandom seeds mean rate: 0.9845 \nRandom seeds max rate:  0.9888 \n```\n\n\n:::\n\n```{.r .cell-code}\nrand2 <- compare_seeds(2, res_lambda2$best_rate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n── λ = 2 ──\nOptimal seed rate:      0.9244 \nRandom seeds mean rate: 0.8985 \nRandom seeds max rate:  0.9252 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Plot\nrand_all <- rbind(\n  transform(rand1, lambda = \"λ=1\"),\n  transform(rand2, lambda = \"λ=2\")\n)\noptimal_lines <- data.frame(\n  lambda   = c(\"λ=1\", \"λ=2\"),\n  opt_rate = c(res_lambda1$best_rate, res_lambda2$best_rate)\n)\n\nggplot(rand_all, aes(x = rate)) +\n  geom_histogram(bins = 20, fill = \"steelblue\", color = \"white\", alpha = 0.8) +\n  geom_vline(data = optimal_lines, aes(xintercept = opt_rate),\n             color = \"red\", linewidth = 1.2, linetype = \"dashed\") +\n  facet_wrap(~lambda, scales = \"free\") +\n  labs(title    = \"Random vs Optimal Seeds: Information Rate\",\n       subtitle = \"Red dashed line = optimal pair rate\",\n       x = \"Information Rate (fraction adopted)\", y = \"Count\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](PS3_networks_files/figure-pdf/unnamed-chunk-9-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n**Left panel**\n\nThe distribution of the random seed rates is concentrated between roughly 0.982 and 0.985, meaning that almost any pair of randomly chosen seeds achieves near-full diffusion. The optimal pair (showed by the red dashed line) is at the right tail but very little above the random average.\n\nIntuitively, when the adoption threshold is 1, a node adopts as soon as any single neighbor has adopted, therefore, the diffusion process is so permissive that seed choice barely matters. The epidemic spreads to almost everyone regardless of where it starts.\n\n**Right panel** There is a dramatic change between the plots. Random seeds now produce a much wider distribution between 0.5 and 0.9 with high variance. Now the optimal pair (also represented by the red dashed line) is at the far right of the distribution, substantially outperforming the average random pair.\n\nNow that the threshold is 2, nodes need at least two neighbors to adopt before switching so the process of diffusion is much more sensitive to the local neighborhood structure of the seeds. Now, high degree seeds places in well-connected parts of the network can immediately expose many nodes to two or more adopters simultaneously, while a randomly chosen pair may sit in a sparse region and fail to reach other nodes beyond the immediate neighbor.\n\nThe main conclusion from the exercise is that optimal seeding matters most when thresholds are high. We have proved that under $\\lambda = 1$ the network is easily activated while with $\\lambda = 2$ the gain from choosing the right seed is substantial. Overall, as adoption becomes harder (higher $\\lambda$), the identity of the initial seed becomes much more important for the final diffusion outcome.\n\n# Routing \n\n## Exercise 3: Routing on Roads\n\nConsider the traffic flow game pictured in the figure below. There are two origin-destination pairs. A unit of traffic needs to flow from the upper left to the upper right, and another unit needs to flow from the lower left to the lower right. The cost functions are given in the figure.\n\n![Figure: Routing Through a Network](routing_q3_ps03.png)\n\n### (a) Socially Optimal Routing & Cost\n\nWhat is the socially optimal routing, and what is its total cost?\n\n**Solution**:\n\nTotal social cost = sum of (flow × cost) across all edges: \n\n$C = x_1(1 + x_1) + x_2(1+x_2) + (2 - x_1 - x_2) \\cdot 3(2 - x_1 -x_2)$\n\nTaking partials and setting equal to zero:\n\n$\\frac{\\partial C} {\\partial x_1} = 1 + 2x_1 − 6(2 − x_1 − x_2) = 0$\n\n$\\frac{\\partial C} {\\partial x_2} = 1 + 2x_2 - 6(2 - x_1 - x_2)= 0$\n\nThis implies that $x_1 = x_2 = x$. Substituting in:\n\n$$\n\\begin{aligned}\n1 + 2x - 6(2 - 2x) &= 0 \\\\\n14x &= 11 \\\\\nx &= \\frac{11}{14}\n\\end{aligned}\n$$\n\nSo $\\frac{11}{14}$ on each direct path, $\\frac{3}{14}$ per origin-destination through the middle.\n\nTotal cost = $14(\\frac{11}{14})^2 − 22(\\frac{11}{14}) + 12 = \\frac{47}{14} \\approx 3.357$\n\n### (b) Equilibrium Routing & Welfare Loss\n\nWhat is the equilibrium routing? What is the welfare loss relative to the optimum?\n\n**Solution:**\n\nAt Wardrop equilibrium, all both paths for each origin-destination pair must have equal user cost; otherwise, drivers would switch.\n\nFor origin-destination 1 (top left to top right), the two path costs are:\n\n  * Direct: $1 + x_1$\n  * Middle: $3(2-x_1 - x_2)$\n  \nBy symmetry, $x_1 = x_2 = x$. Setting both paths equal yields us:\n\n$$\n\\begin{aligned}\n1 + x &= 3(2-2x) \\\\\n1 + x &= 6-6x \\\\\n1 + 7x &= 6 \\\\\n7x &= 5 \\\\\nx &= \\frac{5}{7}\n\\end{aligned}\n$$\n\nThus, each origin-destination pair sends 5/7 direct and 2/7 through the middle.\n\n$$\n\\begin{aligned}\n\\text{Equilibrium cost} &= 2 \\left(\\frac{5}{7}\\right) \\left(1 + \\frac{5}{7}\\right) + \\left(\\frac{4}{7}\\right) 3 \\left(\\frac{4}{7}\\right) \\\\\n&= 2 \\left(\\frac{5}{7}\\right) \\left(\\frac{12}{7}\\right) + \\left(\\frac{4}{7}\\right) \\left(\\frac{12}{7}\\right) \\\\\n&= \\frac{120}{49} + \\frac{48}{49} = \\frac{24}{7} \\approx 3.429\n\\end{aligned}\n$$\n\n$$\n\\text{Welfare loss} = \\frac{24}{7} - \\frac{47}{14} = \\frac{48}{14} - \\frac{47}{14} = \\frac{1}{14} \\approx 0.071\n$$\n\n\n### (c) Tolls and Subsidies\n\nSuppose you can impose constant tolls on some edges and constant subsidies on others. Design a system of tolls and subsidies to implement the social optimum as an equilibrium.\n\n**Solution:**\n\nA Pigouvian toll charges each driver for the externality they impose, based on the extra delay they cause to everyone else on that edge. This is implemented to mitigate the face that the drivers overusing the middle link since they do not pay for the congestion they cause.\n\n$$\n\\text{Toll on edge } e = f_e \\cdot c'_e(f_e) \\text{, evaluated at the social optimum flows.}\n$$\n\n$$\n\\begin{aligned}\n&\\textbf{At the social optimum:} \\\\\n&\\text{Direct edges } (c = 1 + f,\\ c' = 1): \\quad \\tau = \\tfrac{11}{14} \\times 1 = \\tfrac{11}{14} \\\\\n&\\text{Middle edge } (c = 3f,\\ c' = 3): \\quad \\tau = \\tfrac{3}{7} \\times 3 = \\tfrac{9}{7} \\\\\n&\\text{Zero-cost edges}: \\quad \\tau = 0 \\\\[6pt]\n&\\textbf{Verification:} \\\\\n&\\text{Direct path}: \\quad \\left(1 + \\tfrac{11}{14}\\right) + \\tfrac{11}{14} = \\tfrac{25}{14} + \\tfrac{11}{14} = \\tfrac{36}{14} \\\\\n&\\text{Middle path}: \\quad 0 + 3 \\cdot \\tfrac{3}{7} + \\tfrac{9}{7} + 0 = \\tfrac{9}{7} + \\tfrac{9}{7} = \\tfrac{18}{7} = \\tfrac{36}{14} \\\\\n&\\tfrac{36}{14} = \\tfrac{36}{14} \\quad \\Rightarrow \\quad \\text{Paths are equal, so the social optimum is an equilibrium.}\n\\end{aligned}\n$$\n\n# Bonus: Equilibrium Flows\n\n## Exercise 4: Replicate Youn et al 2008\n\n### (a) Import the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nparse_tntp_net <- function(filepath) {\n  lines <- readLines(filepath)\n  \n  # Find the data header line (contains \"init_node\")\n  header_idx <- grep(\"init_node\", lines)[1]\n  \n  # Clean the header line (remove leading ~ and whitespace)\n  header     <- trimws(gsub(\"~|;|\\\\.\", \"\", lines[header_idx]))\n  col_names  <- trimws(strsplit(header, \"\\t\")[[1]])\n  col_names  <- col_names[col_names != \"\"]\n  \n  # Read data lines (everything after the header, skip blanks)\n  data_lines <- lines[(header_idx + 1):length(lines)]\n  data_lines <- data_lines[trimws(data_lines) != \"\"]\n  \n  # Remove trailing semicolons and read\n  data_lines <- gsub(\";\", \"\", data_lines)\n  df <- read.table(text = paste(data_lines, collapse = \"\\n\"),\n                   header = FALSE, fill = TRUE)\n  \n  # Assign column names (drop extra cols if any)\n  df <- df[, 1:length(col_names)]\n  names(df) <- col_names\n  \n  df <- df[!is.na(df$init_node) & !is.na(df$term_node), ]\n  df <- df[df$init_node > 0 & df$term_node > 0, ]\n  return(df)\n}\n\n\n# Now we can load the files\n\nnet_data <- parse_tntp_net(\"Terrassa-Asym_net.tntp\")\ncat(\"Links loaded:\", nrow(net_data), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinks loaded: 3264 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Columns:\", names(net_data), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nColumns: init_node term_node capacity length free_flow_time b power speed toll link_type \n```\n\n\n:::\n:::\n\n\nOnce we have the data loaded, we proceed with the visualization of the igraph objects:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnet_data$v_ij <- 60   # fixed speed as per assignment\n\ng_road <- graph_from_data_frame(\n  d = data.frame(\n    from          = net_data$init_node,\n    to            = net_data$term_node,\n    capacity      = net_data$capacity,\n    length        = net_data$length,\n    free_flow_time = net_data$length / net_data$v_ij,  # d/v in hours\n    b             = net_data$b,\n    power         = net_data$power\n  ),\n  directed = TRUE\n)\n\ncat(\"Nodes:\", vcount(g_road), \"| Edges:\", ecount(g_road), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNodes: 1603 | Edges: 3264 \n```\n\n\n:::\n:::\n\n\nAnd finally plot Terrassa network:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(g_road,\n     layout          = layout_with_fr(g_road),\n     vertex.size     = 2,\n     vertex.label    = NA,\n     edge.arrow.size = 0.1,\n     edge.color      = \"grey60\",\n     vertex.color    = \"steelblue\",\n     main            = \"Terrassa Road Network\")\n```\n\n::: {.cell-output-display}\n![](PS3_networks_files/figure-pdf/unnamed-chunk-12-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n### (b) Nash Equilibrium Flow\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Parse OD trips file\nparse_tntp_trips <- function(filepath) {\n  lines     <- readLines(filepath)\n  nz_line   <- grep(\"NUMBER OF ZONES\", lines, ignore.case = TRUE)[1]\n  n_zones   <- as.integer(gsub(\"[^0-9]\", \"\", lines[nz_line]))\n  cat(\"OD zones:\", n_zones, \"\\n\")\n  \n  od_list         <- list()\n  current_origin  <- NULL\n  \n  for (line in lines) {\n    line <- trimws(line)\n    if (grepl(\"^Origin\", line, ignore.case = TRUE)) {\n      current_origin <- as.integer(gsub(\"[^0-9]\", \"\", line))\n    } else if (!is.null(current_origin) && nchar(line) > 0 && \n               !grepl(\"^<\", line)) {\n      entries <- unlist(strsplit(line, \";\"))\n      for (entry in entries) {\n        entry <- trimws(entry)\n        if (nchar(entry) == 0) next\n        parts <- strsplit(entry, \":\")[[1]]\n        if (length(parts) == 2) {\n          dest   <- as.integer(trimws(parts[1]))\n          demand <- as.numeric(trimws(parts[2]))\n          if (!is.na(dest) && !is.na(demand) && demand > 0)\n            od_list[[length(od_list) + 1]] <- c(current_origin, dest, demand)\n        }\n      }\n    }\n  }\n  do.call(rbind, od_list) |> as.data.frame() |> \n    setNames(c(\"origin\", \"dest\", \"demand\"))\n}\n\nod_data <- parse_tntp_trips(\"Terrassa-Asym_trips.tntp\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOD zones: 55 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"OD pairs with demand:\", nrow(od_data), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOD pairs with demand: 2215 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Total demand:\", sum(od_data$demand), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTotal demand: 25225747 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Setup the edge attributes\nalpha <- 0.2\nbeta  <- 10\nv_ij  <- 60   # fixed speed kph as per assignment\n\n# Extract edge-level data into vectors for fast computation\nE_from     <- as.integer(tail_of(g_road, E(g_road)))\nE_to       <- as.integer(head_of(g_road, E(g_road)))\nd_ij       <- E(g_road)$length      # km\np_ij       <- E(g_road)$capacity    # vehicles\nn_edges    <- ecount(g_road)\nn_nodes    <- vcount(g_road)\n\n# Latency function: l_ij(x) = (d/v) * [1 + alpha*(x/p)^beta]\nlatency <- function(x) {\n  (d_ij / v_ij) * (1 + alpha * (x / p_ij)^beta)\n}\n\n# Potential (Beckmann) function: integral of latency\n# integral_0^x l(t)dt = (d/v)*[x + alpha/(beta+1) * x^(beta+1)/p^beta]\npotential <- function(x) {\n  sum((d_ij / v_ij) * (x + (alpha / (beta + 1)) * x^(beta + 1) / p_ij^beta))\n}\n\n# All-or-nothing assignment\n# Given current costs on edges, load ALL demand onto shortest paths\nall_or_nothing <- function(costs) {\n  E(g_road)$weight <- costs\n  x_aon <- rep(0, n_edges)\n  \n  # Build edge index lookup: (from,to) -> edge index\n  edge_idx <- matrix(0, nrow = n_nodes, ncol = n_nodes)\n  for (e in 1:n_edges) edge_idx[E_from[e], E_to[e]] <- e\n  \n  # For each OD pair, find shortest path and add demand\n  origins <- unique(od_data$origin)\n  for (org in origins) {\n    # All destinations for this origin\n    dests   <- od_data$dest[od_data$origin == org]\n    demands <- od_data$demand[od_data$origin == org]\n    \n    # Single-source shortest paths\n    sp <- shortest_paths(g_road, from = org, to = dests,\n                         weights = E(g_road)$weight, output = \"epath\")\n    \n    for (k in seq_along(dests)) {\n      epath <- as.integer(sp$epath[[k]])\n      if (length(epath) > 0)\n        x_aon[epath] <- x_aon[epath] + demands[k]\n    }\n  }\n  x_aon\n}\n\n# Frank-Wolfe Algorithm\ncat(\"\\nStarting Frank-Wolfe...\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nStarting Frank-Wolfe...\n```\n\n\n:::\n\n```{.r .cell-code}\n# Initialise: load all demand onto free-flow shortest paths\nx <- all_or_nothing(d_ij / v_ij)   # free-flow costs\n\nmax_iter  <- 30\ntol       <- 1e-4\npot_prev  <- Inf\n\nfor (iter in 1:max_iter) {\n  \n  # Step 1: compute current latencies\n  l_current <- latency(x)\n  \n  # Step 2: all-or-nothing on current costs → descent direction y\n  y <- all_or_nothing(l_current)\n  \n  # Step 3: line search — find lambda in [0,1] minimising potential(x + lambda*(y-x))\n  obj_fn <- function(lam) potential(x + lam * (y - x))\n  lam    <- optimise(obj_fn, interval = c(0, 1))$minimum\n  \n  # Step 4: update flows\n  x_new <- x + lam * (y - x)\n  \n  # Convergence check (relative gap)\n  pot_new  <- potential(x_new)\n  rel_gap  <- abs(pot_prev - pot_new) / abs(pot_prev)\n  cat(sprintf(\"Iter %2d | lambda=%.4f | potential=%.4f | rel_gap=%.6f\\n\",\n              iter, lam, pot_new, rel_gap))\n  \n  x <- x_new\n  if (rel_gap < tol && iter > 3) {\n    cat(\"Converged at iteration\", iter, \"\\n\")\n    break\n  }\n  pot_prev <- pot_new\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIter  1 | lambda=0.1126 | potential=264342713571640896128086.0000 | rel_gap=NaN\nIter  2 | lambda=0.0908 | potential=104259876805313189384406.0000 | rel_gap=0.605588\nIter  3 | lambda=0.0988 | potential=37794491004489834692228.0000 | rel_gap=0.637497\nIter  4 | lambda=0.0843 | potential=16905752203090437603248.0000 | rel_gap=0.552693\nIter  5 | lambda=0.0551 | potential=9986317733264699163484.0000 | rel_gap=0.409295\nIter  6 | lambda=0.0724 | potential=5427422641141489598404.0000 | rel_gap=0.456514\nIter  7 | lambda=0.0982 | potential=2631436614761411772486.0000 | rel_gap=0.515159\nIter  8 | lambda=0.0663 | potential=1665274287545940181062.0000 | rel_gap=0.367162\nIter  9 | lambda=0.0766 | potential=1150494935369871917146.0000 | rel_gap=0.309126\nIter 10 | lambda=0.0537 | potential=877696387719389642722.0000 | rel_gap=0.237114\nIter 11 | lambda=0.0575 | potential=725110818794446258266.0000 | rel_gap=0.173848\nIter 12 | lambda=0.0574 | potential=606548833034279321600.0000 | rel_gap=0.163509\nIter 13 | lambda=0.0459 | potential=545848483920816111606.0000 | rel_gap=0.100075\nIter 14 | lambda=0.0476 | potential=494144810992017014804.0000 | rel_gap=0.094722\nIter 15 | lambda=0.0353 | potential=459950677362976882788.0000 | rel_gap=0.069199\nIter 16 | lambda=0.0348 | potential=436260620448087408640.0000 | rel_gap=0.051506\nIter 17 | lambda=0.0477 | potential=403757138531104194560.0000 | rel_gap=0.074505\nIter 18 | lambda=0.0297 | potential=385630184792519671808.0000 | rel_gap=0.044896\nIter 19 | lambda=0.0286 | potential=372291265447800537188.0000 | rel_gap=0.034590\nIter 20 | lambda=0.0323 | potential=357613013323178377226.0000 | rel_gap=0.039427\nIter 21 | lambda=0.0309 | potential=344764676742382354442.0000 | rel_gap=0.035928\nIter 22 | lambda=0.0341 | potential=332078108768383401984.0000 | rel_gap=0.036798\nIter 23 | lambda=0.0251 | potential=322878565763137929226.0000 | rel_gap=0.027703\nIter 24 | lambda=0.0238 | potential=316547000431783510026.0000 | rel_gap=0.019610\nIter 25 | lambda=0.0306 | potential=306525867650850947082.0000 | rel_gap=0.031658\nIter 26 | lambda=0.0242 | potential=299837074361655689226.0000 | rel_gap=0.021821\nIter 27 | lambda=0.0276 | potential=292653694950078218240.0000 | rel_gap=0.023958\nIter 28 | lambda=0.0260 | potential=286122156434115264522.0000 | rel_gap=0.022318\nIter 29 | lambda=0.0255 | potential=280102875322581909504.0000 | rel_gap=0.021037\nIter 30 | lambda=0.0198 | potential=275732599046618513408.0000 | rel_gap=0.015602\n```\n\n\n:::\n\n```{.r .cell-code}\n# Store and show results\nE(g_road)$nash_flow    <- x\nE(g_road)$nash_latency <- latency(x)\nE(g_road)$nash_cost    <- x * latency(x)   # flow * travel time\n\ntotal_nash_cost <- sum(E(g_road)$nash_cost)\ncat(\"\\nTotal Nash flow cost:\", round(total_nash_cost, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nTotal Nash flow cost: 3.033059e+21 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Visualize the flow\n# Colour edges by flow volume\nflow_norm <- (x - min(x)) / (max(x) - min(x))\nedge_cols <- colorRampPalette(c(\"lightblue\", \"orange\", \"red\"))(100)\n\nplot(g_road,\n     layout          = layout_with_fr(g_road),\n     vertex.size     = 2,\n     vertex.label    = NA,\n     edge.arrow.size = 0.1,\n     edge.color      = edge_cols[ceiling(flow_norm * 99) + 1],\n     vertex.color    = \"grey30\",\n     main            = \"Terrassa: Nash Equilibrium Flow\\n(blue=low, red=high)\")\n```\n\n::: {.cell-output-display}\n![](PS3_networks_files/figure-pdf/unnamed-chunk-13-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nThe code below applies the algorithm that works in four steps. First it computes the current latencies from flows, then assigns all demands to the shortest paths under those latencies (which is the all or nothing step), it follows by doing a line search to find the optimal step size lambda and finally it move flows in that direction.\n\nThe output **total_nash_cost** is going to be used in part c to compare against networks with individual streets closed.\n\n### (c) Nash Flow Cost Comparisions\n\n\n\n\n### (d) Closing a Street to Decrease NE Cost\n\n\n# Consensus and Influence\n\n## Exercise 5: Opinion Dynamics\n\nDownload the Facebook100 data, containing facebook networks for 100 universities in the US. We want to analyze how the different networks generate different opinion dynamics. Keep the largest component of each network only.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(list=ls())\nlibrary(R.matlab)   # read .mat files\nlibrary(tidygraph)      # optimize data pipeline\n\n# iterate thru files in facebook100\nfolder_path <- file.path(\"C:/Users/T14/7Programming/R/class/networks/problem_sets/ps03/data/facebook100\")\nfile_list <- list.files(path = folder_path, \n                        pattern = \"\\\\.mat$\", \n                        full.names = TRUE)\n\nfacebook_graphs <- list() #init empty matrix\n\nfor (file in file_list){\n  clean_name <- tools::file_path_sans_ext(basename(file)) # extract school name\n  raw_mat <- readMat(file)                                # load in sparse matrix object\n  adj_matrix <- raw_mat$A                                 # extract adj matrix stored as \"A\"\n  tbl_g <- graph_from_adjacency_matrix(                   # convert to igraph object\n    adj_matrix, \n    mode = \"undirected\",\n    diag = FALSE # remove self-loops\n  ) %>% \n    as_tbl_graph()                                        # store as a tidy graph object -- memory efficient\n  facebook_graphs[[clean_name]] <- tbl_g                  # object store in list, end of iteration\n}\n\nrm(raw_mat, adj_matrix, tbl_g)                            # rm temporary objects -- free up memory\nfacebook_graphs$schools <- NULL                           # remove school names vector\n```\n:::\n\n\n### (a) Assumption: 'Listening'\n\nTo simplify things we will assume that each node \"listens\" to all her neighbors (and herself) with the same probability. In other words, we assume that $T_{ij} = \\frac{1}{(1 + d_i)}$ for all $j \\in N_i$ and also $T_{ii} = \\frac{1}{(1 + d_i)}$. The assumption that the node listens to herself with the same weight makes the walk \"lazy,\" which guarantees aperiodicity (which will be needed for convergence to consensus later on).\n\n### (b) Assign Probabilities\n\nWe will simulate innate/original opinions from a uniform(0,1); i.e., we will assign to each node a $p_i(0)$ that is drawn from a uniform random variable. This means that the consensus should land near 0.5 for every network by the LLN (since these networks have thousands of nodes), and any deviation from that is informative about how concentrated the influence is in the network. If a few high-degree nodes happen to have extreme opinions, and those nodes dominate the stationary distribution, we should see the consensus pulled away from the expected value of 0.5.\n\n### (c) Maximum & Median Influence\n\nWe know from the **Convergence to Consensus proposition** (Golub & Jackson) that, if T is irreducible, the following are equivalent:\n\n  1. T is convergent\n  2. T is aperiodic\n  3. T has a unique (positive) left-eigenvector $s$ corresponding to eigenvalue 1 with $\\sum s_i = 1$ such that for every $p \\in [0, 1]^n$:\n  \n$$\n\\left(lim_{t \\rightarrow \\infty} T^t p \\right)_i = sp  \n$$\n  \n  for every individual $i \\in N$. \n  \nFurthermore, we know that **consensus** is defined as: limiting beliefs are all equal to a weighted average of initial beliefs, with agent $i$'s weight (or influence) given by $s_i$.\n\nThe influence vector $s_i$ given by the left eigenvector of $T$:\n\n  - Note that $\\lim_{t \\rightarrow \\infty} T^t p = \\lim_{t \\rightarrow \\infty} T^t (Tp)$\n  - It must be that $sp = sTp$ for every $p \\in [0,1]^n$\n  - This implies that $s = sT$\n  \nThe eigenvector property says that, for all $i$: \n\n$$\ns_i = \\sum_{j \\in N} T_{ji}s_j\n$$\n\n  - The influence of $i$ is the weighted sum of the influences of individuals $j$ that pay attention to $i$\n      - Influence of $j$ is weighted by $T_{ji}$ which is the trust $j$ places on $i$\n\nThus, to impute the influence of a network we must compute the left eigenvector of $T$. So do so, we must find the vector $s$ such that $sT = s \\iff T's = s$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntest <- facebook_graphs$American75\n```\n:::\n\n\nTo find the left-eigenvalue, we must build a function that converges to $s$ after iterating through multiplications of $T'$. We start by giving everyone equal influence, after which we multiply this starting vector by a weighted combination of the values of nodes that listen to it. We then normalize to ensure the values sum to 1. We iterate through this process until we reach some threshold, such that any change in our multiplication step does not significantly update the influence vector values. First, we must build a 'listening' matrix to get an idea of how much each node listens to others.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(Matrix) # fast method: using as_edgelist\n\nlistening_matrix <- function(graph_obj){ # input: graph (network) object\n  n = vcount(graph_obj)\n  degree = degree(graph_obj)\n  weight = 1 / (1 + degree) # via assumption from part (a)\n  \n  edgelist <- as_edgelist(graph_obj)                             # two-column matrix of edges\n  rows <- c(1:n, edgelist[,1], edgelist[,2])                     # diagonal + both directions\n  cols <- c(1:n, edgelist[,2], edgelist[,1])                   \n  vals <- c(weight, weight[edgelist[,1]], weight[edgelist[,2]])  # self-loops; i listen to j; j listen to i\n  \n  sparseMatrix(i = rows, # return of a sparse matrix of final listening matx\n               j = cols, \n               x = vals, \n               dims = c(n, n))\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# sanity check\ntest_listening_mat <- listening_matrix(test)\ntest_listening_mat[1:10, 1:10] # looks good\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n10 x 10 sparse Matrix of class \"dgCMatrix\"\n                                                                       \n [1,] 0.01470588 .         .          .          .           .         \n [2,] .          0.1111111 .          .          .           .         \n [3,] .          .         0.01960784 .          .           .         \n [4,] .          .         .          0.01408451 .           .         \n [5,] .          .         .          .          0.008064516 .         \n [6,] .          .         .          .          .           0.01470588\n [7,] .          .         .          .          .           .         \n [8,] .          .         .          .          .           .         \n [9,] .          .         .          .          .           .         \n[10,] .          .         .          .          0.008771930 .         \n                                                  \n [1,] .           .         .          .          \n [2,] .           .         .          .          \n [3,] .           .         .          .          \n [4,] .           .         .          .          \n [5,] .           .         .          0.008064516\n [6,] .           .         .          .          \n [7,] 0.002747253 .         .          .          \n [8,] .           0.1111111 .          .          \n [9,] .           .         0.04347826 .          \n[10,] .           .         .          0.008771930\n```\n\n\n:::\n:::\n\n\nNow that our listening matrix function works well, we will build the left-eigenvalue function, which takes this listening matrix as an input, as well as optional arguments regarding the tolerance (how much the influence vector changes for the function to return) as well as the max number of iterations through the function (set as 10_000)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleft_eigenvector <- function(listening_mx,                 # inputs: - listening matrix       \n                            tol = 0.00001,                #         - threshold to determine convergence\n                            max_it = 10000){              #         - max num iterations thru loop\n  n <- nrow(listening_mx)   # num of rows in tmat (corresponds to )\n  s <- rep(1/n, n)          # set starting influence vector as equal across all nodes\n  T_trans <- t(listening_mx) # transpose listening mat to perform T's\n  for (i in seq_len(max_it)) { # iterative process: keep updating s until we 'converge'\n    s_new <- T_trans %*% s               # matrix multpl\n    s_new <- s_new / sum(s_new)          # normalize\n    if (max(abs(s_new - s)) < tol) break # stop condition only if we hit below arbitrary threshold value\n    s <- s_new                           # update s vector as newly multiplied vect\n  }\n  return(as.vector(s_new))\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# sanity check\ntest_lft_eigen <- left_eigenvector(listening_mx = test_listening_mat)\nlength(test_lft_eigen) == vcount(test) # should match num nodes from original network: yes\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# loop over all networks, collect all influence scores\nall_influences <- c()\nfor (name in names(facebook_graphs)) {\n  g <- facebook_graphs[[name]]    # extract graph object from specified matrix\n  T_mat <- listening_matrix(g)    # get associated lsitening mat\n  s <- left_eigenvector(T_mat)    # get associated left-eigenvector\n  all_influences <- c(all_influences, s) # append to list\n}\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# histogram\nhist(all_influences, breaks = 500, col = \"goldenrod\",\n     main = \"Influence Distribution Across Facebook100 Networks\",\n     xlab = \"Influence score\", ylab = \"Frequency\", xlim = c(0, 0.0012))\n```\n\n::: {.cell-output-display}\n![](PS3_networks_files/figure-pdf/unnamed-chunk-14-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n# summary stats\ncat(\"max influence:   \", max(all_influences), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmax influence:    0.008119159 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"median influence:\", median(all_influences), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmedian influence: 4.401269e-05 \n```\n\n\n:::\n:::\n\n\nAfter plotting, we notice that the influence is highly skewed across nodes, with our histogram displaying a strong right-skew, with majority of the observations lying near very low influence (left of the median of 0.000044) and a max value ranging to 0.008. This suggests a power-law like structure, which we can check by plotting the complementary CDF:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- data.frame(influence = sort(all_influences, \n                                  decreasing = TRUE)) # arrange influence in desc order\ndf$rank <- 1:nrow(df)                                 # rank given as row number\ndf$ccdf <- df$rank / nrow(df)                         # calc complementary cdf val as: (rank)/(total # of obs)\n\nggplot(df, aes(x = influence, y = ccdf)) +\n  geom_point(size = 0.3, color = \"salmon\") +\n  scale_x_log10() +\n  scale_y_log10() +   # log-log scale\n  labs(x = \"Influence (log)\", y = \"PDF (log)\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](PS3_networks_files/figure-pdf/unnamed-chunk-15-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nThe plot suggests that perhaps the distribution follows a log-normal structure, or some other family of exponential functions.\n\n### (d) Histogram of Consensus Opinions\n\nTo plot a histogram of the consensus opinions, we need to generate the consensus opinions given by the relationship $\\sum_{j \\in P} s_jp_j(0)$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# consensus vector\nconsensus <- c()\nfor (name in names(facebook_graphs)) {\n  g     <- facebook_graphs[[name]]       # extract graph network\n  T_mat <- listening_matrix(g)           # generate listening matrix\n  s     <- left_eigenvector(T_mat)       # find left eigenvector\n  p0    <- runif(vcount(g))              # random initial opinions (random uniform based on n nodes)\n  consensus <- c(consensus, sum(s * p0)) # s · p0: store in consensus vector\n}\n\n# sanity check\nlength(consensus) # 100; checks out\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 100\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# histogram\nggplot(data.frame(consensus = consensus), aes(x = consensus)) +\n  geom_histogram(bins = 25, fill = \"forestgreen\", color = \"white\") +\n  labs(x = \"Consensus opinion p(inf)\", y = \"Number of networks\",\n       title = \"Consensus Opinions Across Facebook100 Networks\") +\n  theme_bw() +\n  theme(plot.title = element_text(hjust=0.5))\n```\n\n::: {.cell-output-display}\n![](PS3_networks_files/figure-pdf/consensus plotting-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n# modal bin\nh <- hist(consensus, breaks = 25, plot = FALSE) # calculate hist values without plotting\nmodal_mid <- h$mids[which.max(h$counts)]        # extra max counts from each bin\ncat(\"modal consensus opinion:\", round(modal_mid, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmodal consensus opinion: 0.5 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"mean consensus opinion: \", round(mean(consensus), 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmean consensus opinion:  0.4998 \n```\n\n\n:::\n:::\n\n\nThe histogram shows that consensus opinions are tightly concentrated around 0.5 across all 100 networks, with a modal value of 0.501 and a mean of 0.5006. This is to be expected, as initial opinions are drawn iid from unif(0,1) dist with mean 0.5, and the influence weights sum to 1, the consensus $\\sum_j s_j p_j(0)$ is a weighted average of many independent draws, which concentrates around 0.5 by LLN.\n\n### (e) Speed of Learning Calculation\n\nNow we want to calculate the speed of learning. For each network, calculate the first period,\n\n$t^*$, where $\\left(\\sum_i \\tilde{d}_i(A)(p_i(t) - p_i(\\infty))^2 \\right)^{\\frac{1}{2}} < \\varepsilon$ for $\\epsilon = 0.1$ and $\\tilde{d}_i(A) = \\frac{d_i(A)}{\\sum_i d_i(A)}$.\n\nTo do so, we simply calculate the time it takes to converge for a network:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconvergence_time <- function(T_mat, p0, s, g, epsilon = 0.1) {\n  consensus <- sum(s * p0)                # p_i(\\infty)\n  deg       <- degree(g)                  # d_i\n  d_tilde   <- deg / sum(deg)             # \\tilde{d}_i = d_i / \\sum_i d_i\n  p         <- p0                         # start at initial opinions\n  \n  for (t in 1:10000) {\n    p     <- as.vector(T_mat %*% p)       # one round: everyone updates\n    diff  <- p - consensus                # how far each node is from consensus\n    error <- sqrt(sum(d_tilde * diff^2))  # weighted error\n    if (error < epsilon) return(t)        # done? exit condition\n  }\n  return(NA)\n}\n```\n:::\n\n\nAfter which, we apply to all 100 networks.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt_stars <- c() # init empty results list\nfor (name in names(facebook_graphs)) {\n  g     <- facebook_graphs[[name]]\n  T_mat <- listening_matrix(g)\n  s     <- left_eigenvector(T_mat)\n  p0    <- runif(vcount(g))\n  t_star <- convergence_time(T_mat, p0, s, g) # t-star: how many iterations it takes to converge\n  t_stars <- c(t_stars, t_star)               # append to our results list\n}\n\n# results\nresults <- data.frame(network = names(facebook_graphs), t_star = t_stars)\nresults <- results[order(results$t_star), ]\nhead(results)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     network t_star\n1 American75      1\n2  Amherst41      1\n3   Auburn71      1\n4   Baylor93      1\n5       BC17      1\n6 Berkeley13      1\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Fastest convergence:\", min(t_stars), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFastest convergence: 1 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Slowest convergence:\", max(t_stars), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSlowest convergence: 1 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Median convergence: \", median(t_stars, na.rm = TRUE), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMedian convergence:  1 \n```\n\n\n:::\n:::\n\n\nWe see from the results that given an initial value $\\epsilon = 0.1$, all of our networks converge within one iteration, meaning that a single round of local averaging is sufficient to bring opinions within 0.1 of consensus across all 100 networks. This is because the networks are sufficiently large, so the degree-weighted averaging in one step already smooths out most of the disagreement from the random initial opinions.\n\n### (f) Second Eigenvalue Plot\n\nWe want to understand the relationship between network structure and the speed of learning. The second largest eigenvalue $\\lambda_2$ of the listening matrix $T$ governs the rate at which opinions converge; specifically, disagreement decays at rate $\\lambda_2^t$, so networks with $\\lambda_2$ closer to 1 converge more slowly.\n\nFor each network, we compute the two largest eigenvalues of $T$. The first eigenvalue is always 1, guaranteed by the row-stochastic property of $T$ (each row sums to 1, making $\\mathbf{1}$ a right eigenvector with eigenvalue 1). The Perron-Frobenius theorem additionally guarantees that this is the dominant eigenvalue for irreducible non-negative matrices. We then take the modulus of the second eigenvalue $\\lambda_2$.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(RSpectra) # library for computing eigenvalues of large sparse matrices\n\n# compute the second largest eigenvalue (lambda2) for each network\nlambda2s <- c()                                    # init empty vector to store lambda2 vals\nfor (name in names(facebook_graphs)) {             # loop over each uni\n  g     <- facebook_graphs[[name]]                 # extract graph object\n  T_mat <- listening_matrix(g)                     # build the listening matrix\n  eigs  <- eigs(T_mat, k = 2, which = \"LM\")        # compute top 2 eigenvalues by largest magnitude\n  lambda2s <- c(lambda2s, Mod(eigs$values[2]))     # modulus of 2nd eigenvalue (handles complex values)\n}\n```\n:::\n\n\nWe compute the convergence time $t^*$ for each network at three progressively stricter thresholds: $\\varepsilon = 0.1, 0.01, 0.001$. For each network and threshold, we generate random initial opinions from a unif$(0,1)$ distribution, after which we run the opinion dynamics $p(t) = Tp(t-1)$ iteratively, and record the first period $t$ at which the degree-weighted error falls below $\\varepsilon$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# compute t* for multiple epsilon thresholds to see how strictness affects convergence\nepsilons <- c(0.1, 0.01, 0.001)                    # three thresholds for eps\nall_results <- data.frame()                        # init df to store results\n\nfor (eps in epsilons) {                                        # loop over each epsilon value\n  t_stars <- c()                                               # init empty vector for this epsilon's t* values\n  for (name in names(facebook_graphs)) {                       # loop over each school\n    g     <- facebook_graphs[[name]]                           # extract graph object\n    T_mat <- listening_matrix(g)                               # build listening matrix\n    s     <- left_eigenvector(T_mat)                           # compute influence vector\n    p0    <- runif(vcount(g))                                  # generate random initial opinions\n    t_star <- convergence_time(T_mat, p0, s, g, epsilon = eps) # compute convergence time\n    t_stars <- c(t_stars, t_star)                              # append t* for this network\n  }\n  all_results <- rbind(all_results, data.frame(    # bind results for this epsilon to the full df\n    lambda2 = lambda2s,                            # second eigenvalue\n    t_star  = t_stars,                             # convergence time\n    epsilon = paste0(\"epsilon = \", eps)                \n  ))\n}\n```\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# plot: lambda2 vs t* by each epsilon\nggplot(all_results, aes(x = lambda2, y = t_star)) +\n  geom_point() +\n  geom_smooth(method = \"lm\", se = FALSE, linetype = \"dashed\") +\n  facet_wrap(~epsilon, scales = \"free_y\") + # separate panel per epsilon, y-axis scales independently\n  labs(x = expression(lambda[2]),\n       y = expression(t^\"*\"),\n       title = expression(paste(\"Convergence Time vs \", lambda[2]))) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](PS3_networks_files/figure-pdf/unnamed-chunk-20-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nAt $\\varepsilon = 0.1$, all networks converge within a single iteration, meaning that the threshold is too lenient given the size and density of the Facebook100 networks. As we lower $\\varepsilon$, convergence times increase and a clear positive relationship with $\\lambda_2$ emerges. This suggests that networks whose second eigenvalue is closer to 1 take more rounds to reach consensus, confirming that $\\lambda_2$ governs the speed of learning. A value of $\\lambda_2$ near 1 indicates high modularity, meaning that loosely connected communities create a bottleneck that slows the diffusion of opinions across the network.\n\n\n\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}